/* Kimia Express SARL — all site content (French + English).
   Fictitious courier company built for demonstration. Every figure, price, person and shipment is illustrative.
   Prices, zones, cities, relay points, sample shipments and the script strings (js) also drive the estimator,
   booking and tracking tools: build-kimia.js writes them to data.js.
   To deliver to a client: replace values here, drop their PDFs into docs/ and point data-doc links at them. */
"use strict";
module.exports = {
  company: {
    name: "Kimia Express",
    legal: "Kimia Express SARL",
    tagline: { fr: "Livraison · Colis · Logistique", en: "Delivery · Parcels · Logistics" },
    hq: { fr: "12, avenue du Port, Gombe, Kinshasa, RD Congo", en: "12 avenue du Port, Gombe, Kinshasa, DR Congo" },
    phone: "+243 81 000 20 00",
    whatsapp: "+243 81 000 20 01",
    business: "+243 81 000 20 02",
    couriers: "+243 81 000 20 03",
    email: "bonjour@kimia-express.cd",
    businessEmail: "entreprises@kimia-express.cd",
    claimsEmail: "reclamations@kimia-express.cd",
    jobsEmail: "recrutement@kimia-express.cd",
    press: "presse@kimia-express.cd",
    api: "api@kimia-express.cd",
    rccm: "CD/KNG/RCCM/19-B-04512", idnat: "01-H5300-N84125P", nif: "A1907733K",
    domain: "kimia-express.cd"
  },
  facts: [
    { v: { fr: "2,1 M", en: "2.1 M" }, fr: "colis livrés en 2025", en: "parcels delivered in 2025" },
    { v: { fr: "96,8 %", en: "96.8%" }, fr: "livrés à l'heure sur 90 jours", en: "delivered on time, last 90 days" },
    { v: "38 min", fr: "de délai moyen de collecte à Kinshasa", en: "average pickup time in Kinshasa" },
    { v: "12", fr: "villes et 28 points relais", en: "cities and 28 relay points" }
  ],
  figures: [
    { v: { fr: "1 450", en: "1,450" }, fr: "coursiers, agents et salariés", en: "couriers, agents and staff" },
    { v: "620", fr: "coursiers à moto à Kinshasa", en: "motorbike couriers in Kinshasa" },
    { v: { fr: "2 500 m²", en: "2,500 m²" }, fr: "d'entrepôt au hub de Masina", en: "of warehouse at the Masina hub" },
    { v: { fr: "3 400", en: "3,400" }, fr: "entreprises clientes", en: "business customers" }
  ],

  /* ---------- pricing engine (used by the estimator, booking and pricing tables) ---------- */
  rate: 2850,
  sizes: [
    { key: "env", max: 0.5, t: { fr: "Enveloppe", en: "Envelope" }, sub: { fr: "Documents, jusqu'à 0,5 kg", en: "Documents, up to 0.5 kg" } },
    { key: "s", max: 5, t: { fr: "Petit colis", en: "Small parcel" }, sub: { fr: "Jusqu'à 5 kg · 40 × 30 × 20 cm", en: "Up to 5 kg · 40 × 30 × 20 cm" } },
    { key: "m", max: 15, t: { fr: "Moyen colis", en: "Medium parcel" }, sub: { fr: "Jusqu'à 15 kg · 50 × 40 × 35 cm", en: "Up to 15 kg · 50 × 40 × 35 cm" } },
    { key: "l", max: 30, t: { fr: "Grand colis", en: "Large parcel" }, sub: { fr: "Jusqu'à 30 kg · 70 × 50 × 40 cm", en: "Up to 30 kg · 70 × 50 × 40 cm" } }
  ],
  prices: {
    urban: { env: 5000, s: 8000, m: 14000, l: 22000 }, zoneStep: 3000, urbanExpress: 1.5,
    road: { env: 15000, s: 25000, m: 45000, l: 70000 },
    air: { env: 30000, s: 55000, m: 120000, l: 210000 }, intercityExpress: 1.4,
    relayUrban: 1000, relayIntercity: 5000,
    insuredIncluded: 500000, insuranceRate: 0.01,
    codRate: 0.02, codMin: 1000,
    regionalDays: { west: 1, katanga: 1, kivu: 1, kasai: 2 },
    sim: { urbanAvg: 9500, interAvg: 40000, tiers: [[50, 0.10], [200, 0.18], [1000, 0.25]] }
  },
  cities: [
    { key: "kin", n: "Kinshasa", prov: "Kinshasa", mode: "hub", days: 0, region: "west", urban: true, lon: 15.31, lat: -4.32,
      communes: [["Gombe", 1], ["Kinshasa", 1], ["Barumbu", 1], ["Lingwala", 1], ["Kintambo", 1], ["Kasa-Vubu", 1], ["Ngiri-Ngiri", 1], ["Bandalungwa", 1], ["Kalamu", 1],
        ["Ngaliema", 2], ["Lemba", 2], ["Limete", 2], ["Matete", 2], ["Makala", 2], ["Selembao", 2], ["Bumbu", 2], ["Ngaba", 2], ["Kisenso", 2],
        ["Masina", 3], ["Ndjili", 3], ["Kimbanseke", 3], ["Mont-Ngafula", 3], ["Nsele", 3], ["Maluku", 3]] },
    { key: "mat", n: "Matadi", prov: "Kongo Central", mode: "road", days: 1, region: "west", lon: 13.46, lat: -5.82 },
    { key: "boma", n: "Boma", prov: "Kongo Central", mode: "road", days: 1, region: "west", lon: 13.05, lat: -5.85 },
    { key: "kik", n: "Kikwit", prov: "Kwilu", mode: "road", days: 2, region: "west", lon: 18.82, lat: -5.04 },
    { key: "lub", n: "Lubumbashi", prov: "Haut-Katanga", mode: "air", days: 2, region: "katanga", urban: true, lon: 27.48, lat: -11.66,
      communes: [["Lubumbashi", 1], ["Kampemba", 1], ["Kamalondo", 1], ["Kenya", 1], ["Katuba", 2], ["Rwashi", 2], ["Annexe", 2]] },
    { key: "kol", n: "Kolwezi", prov: "Lualaba", mode: "air", days: 3, region: "katanga", lon: 25.47, lat: -10.71 },
    { key: "goma", n: "Goma", prov: "Nord-Kivu", mode: "air", days: 2, region: "kivu", urban: true, lon: 29.22, lat: -1.68,
      communes: [["Goma", 1], ["Karisimbi", 1]] },
    { key: "buk", n: "Bukavu", prov: "Sud-Kivu", mode: "air", days: 2, region: "kivu", lon: 28.86, lat: -2.49 },
    { key: "kis", n: "Kisangani", prov: "Tshopo", mode: "air", days: 2, region: "kis", lon: 25.19, lat: 0.52 },
    { key: "mbm", n: "Mbuji-Mayi", prov: "Kasaï-Oriental", mode: "air", days: 2, region: "kasai", lon: 23.6, lat: -6.13 },
    { key: "kga", n: "Kananga", prov: "Kasaï-Central", mode: "air", days: 2, region: "kasai", lon: 22.42, lat: -5.9 },
    { key: "mbk", n: "Mbandaka", prov: "Équateur", mode: "air", days: 3, region: "mbk", lon: 18.26, lat: 0.05 }
  ],
  cityCards: [
    { key: "kin", img: "street.jpg", d: { fr: "Hub central à Masina, agence à la Gombe, 14 points relais. Livraison à moto dans les 24 communes.", en: "Central hub in Masina, office in Gombe, 14 relay points. Motorbike delivery across all 24 communes." } },
    { key: "lub", img: "lubumbashi.jpg", d: { fr: "Vol cargo quotidien depuis N'djili. Livraison à moto dans les 7 communes, navette routière vers Kolwezi.", en: "Daily cargo flight from N'djili. Motorbike delivery across the 7 communes, road shuttle to Kolwezi." } },
    { key: "goma", img: "goma.jpg", d: { fr: "Vol cargo quotidien. Livraison à moto à Goma et Karisimbi, navette vers Bukavu trois fois par semaine.", en: "Daily cargo flight. Motorbike delivery in Goma and Karisimbi, shuttle to Bukavu three times a week." } },
    { key: "buk", img: "bukavu.jpg", d: { fr: "Agence à Ibanda. Colis par avion depuis Kinshasa ou par la route depuis Goma.", en: "Office in Ibanda. Parcels by air from Kinshasa or by road from Goma." } },
    { key: "kis", img: "kisangani.jpg", d: { fr: "Fret aérien cinq fois par semaine. Colis lourds par barge, sur devis.", en: "Air freight five times a week. Heavy parcels by barge, on quotation." } },
    { key: "mbm", img: "mbujimayi.jpg", d: { fr: "Fret aérien quatre fois par semaine, liaison routière avec Kananga.", en: "Air freight four times a week, road link with Kananga." } },
    { key: "kga", img: "kananga.jpg", d: { fr: "Fret aérien trois fois par semaine, liaison routière avec Mbuji-Mayi.", en: "Air freight three times a week, road link with Mbuji-Mayi." } },
    { key: "boma", img: "boma.jpg", d: { fr: "Camion quotidien sur la N1 via Matadi, départ du hub de Masina à 5 h.", en: "Daily truck on the N1 via Matadi, leaving the Masina hub at 5 am." } },
    { key: "mbk", img: "river.jpg", d: { fr: "Fret aérien trois fois par semaine, barges pour les colis de plus de 100 kg.", en: "Air freight three times a week, barges for parcels over 100 kg." } }
  ],
  relays: [
    { city: "kin", c: "Masina", kind: "hub", n: "Hub central Kimia", a: { fr: "Boulevard Lumumba, arrêt Pascal", en: "Boulevard Lumumba, Pascal stop" }, h: { fr: "Dépôt 24 h/24 · retrait 6 h – 22 h", en: "Drop-off 24/7 · collection 6 am – 10 pm" }, s: ["depot", "retrait", "paiement"] },
    { city: "kin", c: "Gombe", kind: "agence", n: "Agence Kimia Gombe", a: { fr: "12, avenue du Port (siège)", en: "12 avenue du Port (head office)" }, h: { fr: "Lun–sam · 7 h 30 – 19 h", en: "Mon–Sat · 7.30 am – 7 pm" }, s: ["depot", "retrait", "paiement"] },
    { city: "kin", c: "Ndjili", kind: "agence", n: "Agence Kimia Aéroport", a: { fr: "Aéroport de N'djili, zone fret", en: "N'djili Airport, cargo area" }, h: { fr: "7 j/7 · 6 h – 20 h", en: "Daily · 6 am – 8 pm" }, s: ["depot", "retrait", "paiement"] },
    { city: "kin", c: "Kalamu", kind: "relais", n: "Kiosque Kimia Victoire", a: { fr: "Rond-point Victoire, côté Matonge", en: "Rond-point Victoire, Matonge side" }, h: { fr: "7 j/7 · 8 h – 21 h", en: "Daily · 8 am – 9 pm" }, s: ["depot", "retrait", "paiement"] },
    { city: "kin", c: "Limete", kind: "relais", n: "Alimentation La Grâce", a: { fr: "Boulevard Lumumba, 10e rue", en: "Boulevard Lumumba, 10e rue" }, h: { fr: "Lun–sam · 7 h – 20 h", en: "Mon–Sat · 7 am – 8 pm" }, s: ["depot", "retrait"] },
    { city: "kin", c: "Ngaliema", kind: "relais", n: "Cyber Elikya", a: { fr: "Rond-point UPN", en: "UPN roundabout" }, h: { fr: "Lun–sam · 8 h – 20 h", en: "Mon–Sat · 8 am – 8 pm" }, s: ["depot", "retrait", "paiement"] },
    { city: "kin", c: "Lemba", kind: "relais", n: "Librairie Bomoko", a: { fr: "Arrêt Lemba Terminus", en: "Lemba Terminus stop" }, h: { fr: "Lun–sam · 8 h – 19 h", en: "Mon–Sat · 8 am – 7 pm" }, s: ["depot", "retrait"] },
    { city: "kin", c: "Bandalungwa", kind: "relais", n: "Pharmacie Tosalisana", a: { fr: "Avenue Kasa-Vubu, arrêt Bandal Tshibangu", en: "Avenue Kasa-Vubu, Bandal Tshibangu stop" }, h: { fr: "7 j/7 · 8 h – 22 h", en: "Daily · 8 am – 10 pm" }, s: ["retrait", "paiement"] },
    { city: "kin", c: "Kintambo", kind: "relais", n: "Boutique Mama Nzuzi", a: { fr: "Rond-point Kintambo Magasin", en: "Kintambo Magasin roundabout" }, h: { fr: "Lun–sam · 7 h – 19 h", en: "Mon–Sat · 7 am – 7 pm" }, s: ["depot", "retrait"] },
    { city: "kin", c: "Matete", kind: "relais", n: "Alimentation Mboka", a: { fr: "Marché de Matete, entrée principale", en: "Matete market, main entrance" }, h: { fr: "Lun–sam · 7 h – 18 h", en: "Mon–Sat · 7 am – 6 pm" }, s: ["depot", "retrait"] },
    { city: "kin", c: "Mont-Ngafula", kind: "relais", n: "Station Kimia Mitendi", a: { fr: "Route de Matadi, arrêt Mitendi", en: "Route de Matadi, Mitendi stop" }, h: { fr: "Lun–sam · 7 h – 19 h", en: "Mon–Sat · 7 am – 7 pm" }, s: ["depot", "retrait", "paiement"] },
    { city: "kin", c: "Kimbanseke", kind: "relais", n: "Cabine Kimia Mokali", a: { fr: "Quartier Mokali, avenue de la Paix", en: "Mokali, avenue de la Paix" }, h: { fr: "Lun–sam · 8 h – 19 h", en: "Mon–Sat · 8 am – 7 pm" }, s: ["depot", "retrait"] },
    { city: "kin", c: "Ngiri-Ngiri", kind: "relais", n: "Papeterie Elonga", a: { fr: "Avenue Assossa", en: "Avenue Assossa" }, h: { fr: "Lun–sam · 8 h – 18 h", en: "Mon–Sat · 8 am – 6 pm" }, s: ["depot", "retrait"] },
    { city: "kin", c: "Selembao", kind: "relais", n: "Boutique Lisanga", a: { fr: "Avenue By-Pass, arrêt Selembao", en: "Avenue By-Pass, Selembao stop" }, h: { fr: "Lun–sam · 8 h – 19 h", en: "Mon–Sat · 8 am – 7 pm" }, s: ["depot", "retrait"] },
    { city: "lub", c: "Lubumbashi", kind: "agence", n: "Agence Kimia Lubumbashi", a: { fr: "Avenue Mama Yemo, centre-ville", en: "Avenue Mama Yemo, city centre" }, h: { fr: "Lun–sam · 7 h 30 – 18 h 30", en: "Mon–Sat · 7.30 am – 6.30 pm" }, s: ["depot", "retrait", "paiement"] },
    { city: "lub", c: "Kampemba", kind: "relais", n: "Pharmacie Upendo", a: { fr: "Quartier Bel-Air", en: "Bel-Air district" }, h: { fr: "7 j/7 · 8 h – 21 h", en: "Daily · 8 am – 9 pm" }, s: ["depot", "retrait"] },
    { city: "lub", c: "Annexe", kind: "agence", n: "Agence Kimia Luano", a: { fr: "Aéroport de la Luano, zone fret", en: "Luano Airport, cargo area" }, h: { fr: "7 j/7 · 6 h – 18 h", en: "Daily · 6 am – 6 pm" }, s: ["depot", "retrait", "paiement"] },
    { city: "goma", c: "Goma", kind: "agence", n: "Agence Kimia Goma", a: { fr: "Boulevard Kanyamuhanga", en: "Boulevard Kanyamuhanga" }, h: { fr: "Lun–sam · 7 h 30 – 18 h 30", en: "Mon–Sat · 7.30 am – 6.30 pm" }, s: ["depot", "retrait", "paiement"] },
    { city: "goma", c: "Karisimbi", kind: "relais", n: "Boutique Amani", a: { fr: "Rond-point Signers", en: "Signers roundabout" }, h: { fr: "7 j/7 · 8 h – 20 h", en: "Daily · 8 am – 8 pm" }, s: ["depot", "retrait"] },
    { city: "buk", c: "Ibanda", kind: "agence", n: "Agence Kimia Bukavu", a: { fr: "Avenue Patrice-Emery-Lumumba", en: "Avenue Patrice-Emery-Lumumba" }, h: { fr: "Lun–sam · 8 h – 18 h", en: "Mon–Sat · 8 am – 6 pm" }, s: ["depot", "retrait", "paiement"] },
    { city: "mat", c: { fr: "Centre-ville", en: "City centre" }, kind: "agence", n: "Agence Kimia Matadi", a: { fr: "Ville-Haute, près de l'hôpital Kinkanda", en: "Ville-Haute, near Kinkanda hospital" }, h: { fr: "Lun–sam · 7 h 30 – 18 h", en: "Mon–Sat · 7.30 am – 6 pm" }, s: ["depot", "retrait", "paiement"] },
    { city: "boma", c: { fr: "Centre-ville", en: "City centre" }, kind: "relais", n: "Boutique Nzambe Malamu", a: { fr: "Près du marché central", en: "Near the central market" }, h: { fr: "Lun–sam · 8 h – 18 h", en: "Mon–Sat · 8 am – 6 pm" }, s: ["depot", "retrait"] },
    { city: "kik", c: { fr: "Centre-ville", en: "City centre" }, kind: "relais", n: "Alimentation Kwilu", a: { fr: "Quartier Nzinda, près du marché", en: "Nzinda, near the market" }, h: { fr: "Lun–sam · 8 h – 18 h", en: "Mon–Sat · 8 am – 6 pm" }, s: ["depot", "retrait"] },
    { city: "kis", c: { fr: "Centre-ville", en: "City centre" }, kind: "agence", n: "Agence Kimia Kisangani", a: { fr: "Commune de Makiso, centre-ville", en: "Makiso, city centre" }, h: { fr: "Lun–sam · 8 h – 18 h", en: "Mon–Sat · 8 am – 6 pm" }, s: ["depot", "retrait", "paiement"] },
    { city: "mbm", c: { fr: "Centre-ville", en: "City centre" }, kind: "agence", n: "Agence Kimia Mbuji-Mayi", a: { fr: "Rond-point Bonzola", en: "Bonzola roundabout" }, h: { fr: "Lun–sam · 8 h – 18 h", en: "Mon–Sat · 8 am – 6 pm" }, s: ["depot", "retrait", "paiement"] },
    { city: "kga", c: { fr: "Centre-ville", en: "City centre" }, kind: "relais", n: "Librairie Lumière", a: { fr: "Avenue Lumumba, centre-ville", en: "Avenue Lumumba, city centre" }, h: { fr: "Lun–sam · 8 h – 18 h", en: "Mon–Sat · 8 am – 6 pm" }, s: ["depot", "retrait"] },
    { city: "kol", c: { fr: "Centre-ville", en: "City centre" }, kind: "relais", n: "Quincaillerie Manika", a: { fr: "Près du marché de Manika", en: "Near Manika market" }, h: { fr: "Lun–sam · 8 h – 18 h", en: "Mon–Sat · 8 am – 6 pm" }, s: ["depot", "retrait"] },
    { city: "mbk", c: { fr: "Centre-ville", en: "City centre" }, kind: "relais", n: "Boutique Bolingo", a: { fr: "Près du port fluvial", en: "Near the river port" }, h: { fr: "Lun–sam · 8 h – 17 h", en: "Mon–Sat · 8 am – 5 pm" }, s: ["depot", "retrait"] }
  ],
  payments: [
    { key: "mpesa", n: "M-Pesa", mm: true }, { key: "orange", n: "Orange Money", mm: true }, { key: "airtel", n: "Airtel Money", mm: true },
    { key: "afri", n: "Afrimoney", mm: true }, { key: "card", n: "Visa · Mastercard" }, { key: "cash", n: { fr: "Espèces au coursier", en: "Cash to the courier" } }
  ],

  /* ---------- sample shipments for the tracking page ---------- */
  shipments: [
    { id: "KX-2026-418207", fromCity: "kin", toCity: "lub", from: "Gombe, Kinshasa", to: "Kampemba, Lubumbashi", size: "s", weight: "3,2 kg", mode: "air", speed: "std", status: "transit", stage: 2,
      events: [
        { d: "2026-09-14T08:41", t: { fr: "Envoi réservé et payé (M-Pesa)", en: "Shipment booked and paid (M-Pesa)" }, p: "Gombe, Kinshasa" },
        { d: "2026-09-14T09:12", t: { fr: "Collecté par Patrick M.", en: "Picked up by Patrick M." }, p: "Gombe, Kinshasa" },
        { d: "2026-09-14T13:40", t: { fr: "Arrivé au hub central", en: "Arrived at the central hub" }, p: "Masina, Kinshasa" },
        { d: "2026-09-14T21:05", t: { fr: "Embarqué sur le vol cargo KIN → FBM", en: "Loaded on cargo flight KIN → FBM" }, p: { fr: "Aéroport de N'djili", en: "N'djili Airport" } },
        { d: "2026-09-15T08:30", t: { fr: "Arrivé à l'agence de destination", en: "Arrived at the destination office" }, p: { fr: "Aéroport de la Luano, Lubumbashi", en: "Luano Airport, Lubumbashi" } }
      ],
      next: { fr: "Livraison prévue mercredi 16 septembre, entre 9 h et 13 h", en: "Delivery expected Wednesday 16 September, 9 am – 1 pm" } },
    { id: "KX-2026-305116", fromCity: "kin", toCity: "kin", from: "Limete, Kinshasa", to: "Ngaliema, Kinshasa", size: "env", weight: "0,3 kg", mode: "urban", speed: "exp", status: "out", stage: 3,
      events: [
        { d: "2026-09-15T10:02", t: { fr: "Envoi réservé et payé (Orange Money)", en: "Shipment booked and paid (Orange Money)" }, p: "Limete, Kinshasa" },
        { d: "2026-09-15T10:21", t: { fr: "Collecté par Junior K.", en: "Picked up by Junior K." }, p: "Limete, Kinshasa" },
        { d: "2026-09-15T10:58", t: { fr: "En route vers le destinataire", en: "On the way to the recipient" }, p: { fr: "Boulevard du 30 Juin", en: "Boulevard du 30 Juin" } }
      ],
      courier: { n: "Junior K.", v: { fr: "Moto · plaque KN 4417 BH", en: "Motorbike · plate KN 4417 BH" } },
      next: { fr: "Arrivée entre 11 h 20 et 11 h 40", en: "Arriving between 11.20 and 11.40 am" } },
    { id: "KX-2026-221940", fromCity: "goma", toCity: "buk", from: "Karisimbi, Goma", to: "Ibanda, Bukavu", size: "m", weight: "11 kg", mode: "road", speed: "std", status: "delivered", stage: 4,
      events: [
        { d: "2026-09-12T09:30", t: { fr: "Déposé au point relais Boutique Amani", en: "Dropped at the Boutique Amani relay point" }, p: "Karisimbi, Goma" },
        { d: "2026-09-12T16:15", t: { fr: "Parti de l'agence de Goma", en: "Left the Goma office" }, p: "Goma" },
        { d: "2026-09-13T11:05", t: { fr: "Arrivé à l'agence de Bukavu", en: "Arrived at the Bukavu office" }, p: "Ibanda, Bukavu" },
        { d: "2026-09-13T14:20", t: { fr: "En cours de livraison", en: "Out for delivery" }, p: "Bukavu" },
        { d: "2026-09-13T16:47", t: { fr: "Livré, 185 000 FC encaissés", en: "Delivered, 185,000 FC collected" }, p: "Ibanda, Bukavu" }
      ],
      proof: { by: "C. Bahati", at: "2026-09-13T16:47", cod: 185000, payout: { fr: "Reversé le 14 septembre sur M-Pesa", en: "Paid out on 14 September via M-Pesa" } } },
    { id: "KX-2026-190377", fromCity: "kin", toCity: "mat", from: "Ngaliema, Kinshasa", to: "Ville-Haute, Matadi", size: "s", weight: "2 kg", mode: "road", speed: "std", status: "failed", stage: 3,
      events: [
        { d: "2026-09-13T15:10", t: { fr: "Envoi réservé (espèces à la collecte)", en: "Shipment booked (cash at pickup)" }, p: "Ngaliema, Kinshasa" },
        { d: "2026-09-13T16:02", t: { fr: "Collecté par Christelle N.", en: "Picked up by Christelle N." }, p: "Ngaliema, Kinshasa" },
        { d: "2026-09-14T05:00", t: { fr: "Parti du hub central, camion N1", en: "Left the central hub, N1 truck" }, p: "Masina, Kinshasa" },
        { d: "2026-09-14T12:40", t: { fr: "Arrivé à l'agence de Matadi", en: "Arrived at the Matadi office" }, p: "Matadi" },
        { d: "2026-09-14T15:10", t: { fr: "Tentative échouée : destinataire absent, deux appels sans réponse", en: "Attempt failed: recipient absent, two unanswered calls" }, p: "Ville-Haute, Matadi" }
      ],
      next: { fr: "Nouvelle tentative prévue mercredi 16 septembre, ou retrait à l'agence de Matadi", en: "New attempt planned Wednesday 16 September, or collection at the Matadi office" } }
  ],

  services: [
    { key: "urbain", img: "boxes.jpg", from: 5000, t: { fr: "Coursier en ville", en: "City courier" }, delay: { fr: "2 à 6 h · express moins de 2 h", en: "2 to 6 h · express under 2 h" },
      d: { fr: "Documents et colis livrés à moto dans la journée à Kinshasa, Lubumbashi et Goma.", en: "Documents and parcels delivered by motorbike the same day in Kinshasa, Lubumbashi and Goma." } },
    { key: "intervilles", img: "plane.jpg", from: 15000, t: { fr: "Intervilles", en: "Intercity" }, delay: { fr: "J+1 à J+3", en: "1 to 3 days" },
      d: { fr: "Par la route vers Matadi, Boma et Kikwit, par avion vers Lubumbashi, les Kivu, Kisangani et les Kasaï.", en: "By road to Matadi, Boma and Kikwit, by air to Lubumbashi, the Kivus, Kisangani and the Kasaï." } },
    { key: "ecommerce", img: "warehouse.jpg", from: 3750, per: { fr: "par commande", en: "per order" }, t: { fr: "E-commerce", en: "E-commerce" }, delay: { fr: "compte entreprise", en: "business account" },
      d: { fr: "Stockage, préparation, livraison et contre-remboursement reversé en 24 heures.", en: "Storage, packing, delivery and cash on delivery paid out within 24 hours." } },
    { key: "courses", img: "market.jpg", from: 6000, t: { fr: "Courses et pharmacie", en: "Errands and pharmacy" }, delay: { fr: "moins d'une heure", en: "under an hour" },
      d: { fr: "Marché, restaurant, pharmacie : nous achetons et livrons dans le centre de Kinshasa. Achats en plus.", en: "Market, restaurant, pharmacy: we buy and deliver in central Kinshasa. Purchases extra." } }
  ],
  leaders: [
    { n: "Aline Mbala Kabongo", r: { fr: "Cofondatrice et directrice générale", en: "Co-founder and Chief Executive" }, b: { fr: "Ancienne responsable logistique d'un distributeur de boissons. Elle a lancé Kimia en 2019 avec six motos et un numéro WhatsApp.", en: "Former logistics manager at a beverage distributor. She started Kimia in 2019 with six motorbikes and a WhatsApp number." } },
    { n: "Joël Tshimanga Ilunga", r: { fr: "Cofondateur, directeur des opérations", en: "Co-founder, Chief Operating Officer" }, b: { fr: "Dirige les coursiers et les agents, le hub de Masina et les contrats de fret aérien et routier.", en: "Runs the couriers and agents, the Masina hub and the air and road freight contracts." } },
    { n: "Esther Mukendi Lusamba", r: { fr: "Directrice administrative et financière", en: "Chief Financial Officer" }, b: { fr: "Expert-comptable. Responsable des reversements de contre-remboursement, 4 milliards de FC par mois.", en: "Chartered accountant. In charge of cash-on-delivery payouts, 4 billion FC a month." } },
    { n: "Serge Kasongo Mwenze", r: { fr: "Directeur technique", en: "Chief Technology Officer" }, b: { fr: "Ingénieur logiciel formé à Kinshasa et à Kigali. Il a conçu l'application des coursiers, le suivi en direct et l'API.", en: "Software engineer trained in Kinshasa and Kigali. He built the courier app, live tracking and the API." } },
    { n: "Rachel Bahati Kavira", r: { fr: "Directrice régionale Est", en: "Regional Director, East" }, b: { fr: "A ouvert les agences de Goma et de Bukavu en 2023 et les dirige depuis.", en: "Opened the Goma and Bukavu offices in 2023 and has run them since." } },
    { n: "Fabrice Kalenga Ngoy", r: { fr: "Directeur régional Katanga", en: "Regional Director, Katanga" }, b: { fr: "Responsable de Lubumbashi et Kolwezi, et des comptes des sous-traitants miniers.", en: "Responsible for Lubumbashi and Kolwezi, and for mining contractor accounts." } }
  ],
  timeline: [
    { y: 2019, fr: "Six motos, un numéro WhatsApp et un bureau à la Gombe. Premières livraisons de documents pour les cabinets et les banques.", en: "Six motorbikes, a WhatsApp number and an office in Gombe. First document deliveries for law firms and banks." },
    { y: 2020, fr: "Courses, repas et médicaments livrés pendant le confinement. 40 coursiers.", en: "Groceries, meals and medicines delivered during the lockdown. 40 couriers." },
    { y: 2021, fr: "Premiers contrats e-commerce avec contre-remboursement. Entrepôt de Masina.", en: "First e-commerce contracts with cash on delivery. Masina warehouse." },
    { y: 2022, fr: "Ouverture de Matadi et Boma par la route. Application mobile et suivi par SMS.", en: "Matadi and Boma open by road. Mobile app and SMS tracking." },
    { y: 2023, fr: "Fret aérien depuis N'djili. Agences de Lubumbashi, Goma et Bukavu.", en: "Air freight from N'djili. Lubumbashi, Goma and Bukavu offices." },
    { y: 2024, fr: "API pour les boutiques en ligne. Kisangani, Mbuji-Mayi et Kananga. Un million de colis dans l'année.", en: "API for online shops. Kisangani, Mbuji-Mayi and Kananga. One million parcels in the year." },
    { y: 2025, fr: "Kolwezi, Kikwit et Mbandaka. 2,1 millions de colis. Programme Kimia Moto pour les coursiers.", en: "Kolwezi, Kikwit and Mbandaka. 2.1 million parcels. Kimia Moto programme for couriers." },
    { y: 2026, fr: "Contre-remboursement reversé en 24 heures. Trente motos électriques en test.", en: "Cash on delivery paid out within 24 hours. Thirty electric motorbikes on trial." }
  ],
  news: [
    { d: "2026-09-01", cat: { fr: "Produit", en: "Product" }, t: { fr: "Le contre-remboursement est désormais reversé en 24 heures", en: "Cash on delivery is now paid out within 24 hours" }, b: { fr: ["Les montants encaissés par nos coursiers sont reversés aux boutiques le lendemain de la livraison, sur M-Pesa, Orange Money, Airtel Money ou par virement. Le délai était de sept jours.", "Les comptes de plus de 1 000 colis par mois sont payés chaque jour à 18 h."], en: ["Amounts collected by our couriers are paid to shops the day after delivery, via M-Pesa, Orange Money, Airtel Money or bank transfer. The delay used to be seven days.", "Accounts shipping more than 1,000 parcels a month are paid every day at 6 pm."] } },
    { d: "2026-07-14", cat: { fr: "Réseau", en: "Network" }, t: { fr: "Mbandaka rejoint le réseau : avion et barge", en: "Mbandaka joins the network: air and barge" }, b: { fr: ["Trois vols cargo par semaine desservent désormais Mbandaka. Les colis de plus de 100 kg partent par barge depuis Kinshasa, sur devis, en huit à douze jours.", "Le point relais Boutique Bolingo, près du port, reçoit et remet les colis du lundi au samedi."], en: ["Three cargo flights a week now serve Mbandaka. Parcels over 100 kg leave Kinshasa by barge, on quotation, in eight to twelve days.", "The Boutique Bolingo relay point, near the port, receives and hands over parcels Monday to Saturday."] } },
    { d: "2026-06-03", cat: { fr: "Environnement", en: "Environment" }, t: { fr: "Trente motos électriques en test à la Gombe", en: "Thirty electric motorbikes on trial in Gombe" }, b: { fr: ["Pendant six mois, trente coursiers de la Gombe et de Lingwala roulent sur des motos électriques rechargées au hub et à l'agence de la Gombe, avec batteries échangeables.", "Nous mesurons l'autonomie réelle, le coût par course et les pannes avant de décider d'un déploiement plus large."], en: ["For six months, thirty couriers in Gombe and Lingwala ride electric motorbikes charged at the hub and the Gombe office, with swappable batteries.", "We are measuring real range, cost per delivery and breakdowns before deciding on a wider roll-out."] } },
    { d: "2026-03-18", cat: { fr: "Sécurité", en: "Safety" }, t: { fr: "600 coursiers certifiés en sécurité routière", en: "600 couriers certified in road safety" }, b: { fr: ["Tous les coursiers de Kinshasa ont suivi la formation de deux jours : conduite défensive, port du casque et du gilet, transport des charges, conduite sous la pluie.", "Les accidents avec arrêt ont baissé de 41 % sur douze mois."], en: ["All Kinshasa couriers completed the two-day course: defensive riding, helmet and vest, carrying loads, riding in the rain.", "Lost-time accidents fell by 41% over twelve months."] } },
    { d: "2026-02-10", cat: { fr: "Résultats", en: "Results" }, t: { fr: "2,1 millions de colis livrés en 2025", en: "2.1 million parcels delivered in 2025" }, b: { fr: ["Le volume a doublé en un an, porté par le commerce en ligne à Kinshasa et le fret aérien vers Lubumbashi et Goma. 96,8 % des colis ont été livrés dans les délais annoncés.", "Kimia compte 3 400 entreprises clientes et 1 450 coursiers, agents et salariés."], en: ["Volume doubled in a year, driven by online retail in Kinshasa and air freight to Lubumbashi and Goma. 96.8% of parcels were delivered within the announced time.", "Kimia has 3,400 business customers and 1,450 couriers, agents and staff."] } },
    { d: "2025-11-05", cat: { fr: "Produit", en: "Product" }, t: { fr: "Nouvelle application : suivi en direct et lien partageable", en: "New app: live tracking and shareable link" }, b: { fr: ["Le jour de la livraison, le destinataire voit la position du coursier et reçoit un lien de suivi par SMS, sans installer l'application.", "Les expéditeurs peuvent reprogrammer une livraison ou la rediriger vers un point relais en deux clics."], en: ["On delivery day the recipient sees the courier's position and receives a tracking link by SMS, without installing the app.", "Senders can reschedule a delivery or redirect it to a relay point in two clicks."] } }
  ],
  jobs: [
    { t: { fr: "Coursier moto", en: "Motorbike courier" }, city: "Kinshasa", dept: { fr: "Opérations", en: "Operations" }, type: { fr: "Partenaire indépendant · 40 places", en: "Independent partner · 40 places" }, close: "2026-10-31" },
    { t: { fr: "Coursier moto", en: "Motorbike courier" }, city: "Lubumbashi", dept: { fr: "Opérations", en: "Operations" }, type: { fr: "Partenaire indépendant · 15 places", en: "Independent partner · 15 places" }, close: "2026-10-31" },
    { t: { fr: "Chauffeur utilitaire, permis B", en: "Van driver, B licence" }, city: "Kinshasa", dept: { fr: "Opérations", en: "Operations" }, type: { fr: "CDD 12 mois · 6 postes", en: "12-month contract · 6 positions" }, close: "2026-10-09" },
    { t: { fr: "Agent de tri de nuit, hub de Masina", en: "Night sorting agent, Masina hub" }, city: "Kinshasa", dept: { fr: "Hub", en: "Hub" }, type: { fr: "CDI · 10 postes", en: "Permanent · 10 positions" }, close: "2026-09-30" },
    { t: { fr: "Responsable d'agence", en: "Office manager" }, city: "Goma", dept: { fr: "Réseau", en: "Network" }, type: { fr: "CDI", en: "Permanent" }, close: "2026-10-16" },
    { t: { fr: "Conseiller service client, français et lingala", en: "Customer service adviser, French and Lingala" }, city: "Kinshasa", dept: { fr: "Service client", en: "Customer service" }, type: { fr: "CDI · 4 postes", en: "Permanent · 4 positions" }, close: "2026-10-02" },
    { t: { fr: "Développeur backend, API", en: "Backend developer, API" }, city: "Kinshasa", dept: { fr: "Technologie", en: "Technology" }, type: { fr: "CDI · hybride", en: "Permanent · hybrid" }, close: "2026-10-23" },
    { t: { fr: "Chargé de comptes entreprises", en: "Business account manager" }, city: "Lubumbashi", dept: { fr: "Commercial", en: "Sales" }, type: { fr: "CDI", en: "Permanent" }, close: "2026-10-12" }
  ],
  faqs: [
    { cat: "send", q: { fr: "Quelle taille de colis puis-je envoyer ?", en: "What size of parcel can I send?" }, a: { fr: "Jusqu'à 30 kg et 70 × 50 × 40 cm par colis, en ville comme entre les villes. Au-delà, notre service fret prend jusqu'à 500 kg par envoi, sur devis.", en: "Up to 30 kg and 70 × 50 × 40 cm per parcel, within a city or between cities. Beyond that, our freight service takes up to 500 kg per shipment, on quotation." } },
    { cat: "send", q: { fr: "Comment écrire une adresse à Kinshasa ?", en: "How do I write an address in Kinshasa?" }, a: { fr: "Commune, quartier, avenue et numéro si possible, puis un point de repère : église, école, arrêt de bus, couleur du portail. Le coursier appelle le destinataire avant d'arriver.", en: "Commune, district, avenue and number where possible, then a landmark: church, school, bus stop, gate colour. The courier calls the recipient before arriving." } },
    { cat: "send", q: { fr: "Puis-je programmer une collecte ?", en: "Can I schedule a pickup?" }, a: { fr: "Oui, jusqu'à sept jours à l'avance, par créneau de deux heures. Les comptes entreprises peuvent programmer des collectes récurrentes.", en: "Yes, up to seven days ahead, in two-hour slots. Business accounts can schedule recurring pickups." } },
    { cat: "send", q: { fr: "Et si le destinataire est absent ?", en: "What if the recipient is not there?" }, a: { fr: "Le coursier appelle deux fois et attend 10 minutes. Nouvelle tentative gratuite le lendemain, ou retrait en point relais. Après deux échecs, le colis est gardé cinq jours puis retourné.", en: "The courier calls twice and waits 10 minutes. Free second attempt the next day, or collection at a relay point. After two failures the parcel is kept five days, then returned." } },
    { cat: "track", q: { fr: "Je n'ai pas reçu de numéro de suivi.", en: "I did not receive a tracking number." }, a: { fr: "Il est envoyé par SMS dès la confirmation et visible dans l'application. Vérifiez le numéro de téléphone saisi, ou écrivez-nous sur WhatsApp avec le nom de l'expéditeur.", en: "It is sent by SMS as soon as the booking is confirmed and shown in the app. Check the phone number entered, or message us on WhatsApp with the sender's name." } },
    { cat: "track", q: { fr: "Pourquoi mon colis intervilles n'avance pas ?", en: "Why is my intercity parcel not moving?" }, a: { fr: "Les colis par avion attendent le prochain vol cargo disponible. Un vol reporté décale la livraison d'un jour ; vous recevez un SMS dès le nouveau départ.", en: "Air parcels wait for the next available cargo flight. A postponed flight delays delivery by a day; you receive an SMS as soon as it leaves." } },
    { cat: "track", q: { fr: "Puis-je changer l'adresse de livraison ?", en: "Can I change the delivery address?" }, a: { fr: "Oui, tant que le colis n'est pas en cours de livraison, depuis la page de suivi ou par WhatsApp. En ville, un changement de zone peut ajouter 3 000 FC.", en: "Yes, as long as the parcel is not out for delivery, from the tracking page or by WhatsApp. Within a city, a change of zone may add 3,000 FC." } },
    { cat: "pay", q: { fr: "Quels moyens de paiement acceptez-vous ?", en: "Which payment methods do you accept?" }, a: { fr: "M-Pesa, Orange Money, Airtel Money, Afrimoney, Visa et Mastercard, ou espèces au coursier. Les comptes entreprises reçoivent une facture mensuelle.", en: "M-Pesa, Orange Money, Airtel Money, Afrimoney, Visa and Mastercard, or cash to the courier. Business accounts receive a monthly invoice." } },
    { cat: "pay", q: { fr: "Comment fonctionne le contre-remboursement ?", en: "How does cash on delivery work?" }, a: { fr: "Le coursier encaisse le montant auprès du destinataire, en espèces ou en mobile money. Nous le reversons sous 24 heures, moins 2 % de frais (minimum 1 000 FC).", en: "The courier collects the amount from the recipient, in cash or mobile money. We pay it out within 24 hours, less a 2% fee (minimum 1,000 FC)." } },
    { cat: "pay", q: { fr: "Les prix sont-ils en francs ou en dollars ?", en: "Are prices in francs or dollars?" }, a: { fr: "En francs congolais, toutes taxes comprises. L'équivalent en dollars est affiché à titre indicatif, au taux de 2 850 FC pour 1 USD.", en: "In Congolese francs, all taxes included. The dollar equivalent is shown for information, at 2,850 FC to 1 USD." } },
    { cat: "biz", q: { fr: "Comment ouvrir un compte entreprise ?", en: "How do I open a business account?" }, a: { fr: "Remplissez le formulaire de la page Entreprises. Un conseiller vous appelle sous un jour ouvré ; prévoyez le RCCM, l'identification nationale et la pièce d'identité du gérant.", en: "Fill in the form on the Business page. An adviser calls you within one working day; have your RCCM, national ID number and the manager's identity document ready." } },
    { cat: "biz", q: { fr: "Proposez-vous une API ?", en: "Do you offer an API?" }, a: { fr: "Oui : création d'envois, tarifs, suivi, étiquettes et webhooks. L'environnement de test est gratuit ; la documentation est envoyée sur demande à api@kimia-express.cd.", en: "Yes: shipment creation, rates, tracking, labels and webhooks. The test environment is free; documentation is sent on request to api@kimia-express.cd." } },
    { cat: "claim", q: { fr: "Mon colis est arrivé abîmé.", en: "My parcel arrived damaged." }, a: { fr: "Refusez-le si possible, ou prenez des photos devant le coursier. Déposez une réclamation sous 48 heures avec le numéro de suivi.", en: "Refuse it if you can, or take photos in front of the courier. File a claim within 48 hours with the tracking number." } },
    { cat: "claim", q: { fr: "Comment suis-je indemnisé ?", en: "How am I compensated?" }, a: { fr: "Jusqu'à la valeur déclarée, dans la limite de 500 000 FC sans assurance complémentaire. Paiement par mobile money sous dix jours ouvrés après accord.", en: "Up to the declared value, capped at 500,000 FC without extra insurance. Paid by mobile money within ten working days of agreement." } },
    { cat: "claim", q: { fr: "Un coursier m'a demandé de l'argent en plus.", en: "A courier asked me for extra money." }, a: { fr: "Le prix payé à la réservation est définitif. Signalez-le tout de suite au service client : c'est une faute grave.", en: "The price paid at booking is final. Report it to customer service straight away: it is serious misconduct." } }
  ],
  docs: [
    { t: { fr: "Conditions générales de transport", en: "General terms of carriage" }, m: "PDF · 6 p. · 2026" },
    { t: { fr: "Barème des tarifs 2026", en: "2026 price list" }, m: "PDF · 2 p." },
    { t: { fr: "Guide d'emballage", en: "Packing guide" }, m: "PDF · 4 p." },
    { t: { fr: "Politique de confidentialité", en: "Privacy policy" }, m: "PDF · 3 p. · 2026" },
    { t: { fr: "Contrat de service entreprise (modèle)", en: "Business service agreement (template)" }, m: "PDF · 8 p." },
    { t: { fr: "Documentation de l'API v1", en: "API v1 documentation" }, m: "PDF · 24 p." },
    { t: { fr: "Charte du coursier", en: "Courier charter" }, m: "PDF · 4 p. · 2025" }
  ],
  credits: [
    ["Quick delivery by bike, Kinshasa", "Rahul Tilak", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Mode_of_Transport_on_Bike_for_Quick_Delivery_at_Kinshasa,_DRC.jpg"],
    ["Home delivery transport, Kinshasa", "Rahul Tilak", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Mode_of_Transport_for_Home_Delivery_at_Kinshasa,_DRC.jpg"],
    ["GG Mart supermarket, Kinshasa", "Rahul Tilak", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:GG_Mart_Super_Market_at_Kinshasa,_DRC.jpg"],
    ["Kinshasa street", "Marc Vick", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Kinshasa_street.jpg"],
    ["Motorbike taxis, Goma", "Izzobae", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Motorbike_Transport_in_Africa_Motorbike_Taxis.jpg"],
    ["Motorcycle delivery drivers, Nairobi", "Rosiestep", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Motorcycle_delivery_drivers,_Valley_Road,_Nairobi_2025_02.png"],
    ["Boulevard du 30 juin, Kinshasa", "Moyogo", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Kinshasa,_Boulevard_du_30_juin_-_20090701.jpg"],
    ["Kinshasa from the 16th floor", "Irene2005", "CC BY 2.0", "https://commons.wikimedia.org/wiki/File:Kinshasa_from_the_16th_floor.jpg"],
    ["Kinshasa by night", "MONUSCO Photos", "CC BY-SA 2.0", "https://commons.wikimedia.org/wiki/File:Kinshasa_by_night_(23769991270).jpg"],
    ["Traffic jam in Kinshasa", "MONUSCO Photos", "CC BY-SA 2.0", "https://commons.wikimedia.org/wiki/File:Ici_un_embouteillage_%C3%A0_Kinshasa_(15135583779).jpg"],
    ["La Gombe, Kinshasa", "ByaduniaEspoir", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:La_Gombe,_Kinshasa,_RDC.jpg"],
    ["Kinshasa farmers' market", "OussamaHamama", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Kinshasa_Farmers%27_Market.jpg"],
    ["Kinshasa Mall", "Kitangaza.1953", "CC0", "https://commons.wikimedia.org/wiki/File:Kinshasa_Mall,_2024.jpg"],
    ["Mobile money outlet", "Ndiwulira", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Mobile_money_outlet.jpg"],
    ["Warehouse interior", "Shixart1985", "CC BY 2.0", "https://commons.wikimedia.org/wiki/File:Warehouse_interior_showcasing_organized_shelving_and_packages.jpg"],
    ["Shipping carton", "Bradsills", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Verpackung_(34).jpg"],
    ["Filair aircraft, Kikwit", "BlueSalo", "CC BY-SA 3.0", "https://commons.wikimedia.org/wiki/File:Filair_kikwit.jpg"],
    ["Square in Lubumbashi", "T. Thielemans", "CC BY 3.0", "https://commons.wikimedia.org/wiki/File:Square_in_Lubumbashi,_2011.jpg"],
    ["Goma", "Fiston bamela", "CC0", "https://commons.wikimedia.org/wiki/File:Goma_photo.jpg"],
    ["Bukavu centre-ville", "EMMANRMS", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Bukavu_centre_ville.png"],
    ["Kisangani waterfront", "Julien Harneis", "CC BY-SA 2.0", "https://commons.wikimedia.org/wiki/File:Kisangani_water_front.jpg"],
    ["Mbuji-Mayi", "Kitangaza.1953", "CC0", "https://commons.wikimedia.org/wiki/File:Mbuji-Mayi,_DR_Congo.jpg"],
    ["Kananga", "Cedrick ngalula", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Kananga_City.jpg"],
    ["Boma", "Χρίστος Ιμμανοελ", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:Boma_DR_Congo.jpg"],
    ["Congo River", "Leon Bilili", "CC BY-SA 4.0", "https://commons.wikimedia.org/wiki/File:FLEUVE_02.jpg"]
  ],

  ui: {
    fr: {
      demoBar: "Démonstrateur IK Digital Solutions · Kimia Express SARL est une société fictive. Prix, colis, personnes et documents sont illustratifs ; réservations, paiements et SMS sont simulés.",
      back: "← Retour au portfolio", skip: "Aller au contenu", menu: "Menu", navLabel: "Navigation principale",
      util: { care: "Service client 7 j/7", about: "À propos", jobs: "Carrières" },
      nav: [["pricing", "Tarifs"], ["business", "Entreprises"], ["network", "Réseau & points relais"], ["couriers", "Devenir coursier"], ["help", "Aide"]],
      cta: { track: "Suivre", send: "Envoyer un colis" },
      illustrative: "Chiffres illustratifs : société fictive créée pour la démonstration.",
      consent: { text: "Ce site utilise un stockage local pour mémoriser votre langue, vos préférences et vos envois de démonstration. Aucun traceur publicitaire. Conformément au Code du numérique, vous pouvez accepter ou refuser.", yes: "Accepter", no: "Refuser", more: "Politique de données" },
      common: { download: "Télécharger", from: "À partir de", book: "Réserver", more: "En savoir plus", home: "Accueil" },
      quick: { tabQuote: "Estimer un envoi", tabTrack: "Suivre un colis", from: "Départ", to: "Arrivée", commune: "Commune", size: "Colis", speed: "Vitesse", std: "Standard", exp: "Express", price: "Prix estimé", book: "Réserver la collecte", trackLabel: "Numéro de suivi", trackBtn: "Suivre", tryHint: "Essayez KX-2026-418207 ou KX-2026-305116.", note: "Prix TTC, sans frais cachés. Paiement à la confirmation." },
      footer: {
        about: "Livraison express et logistique en RDC depuis 2019 : coursiers à moto à Kinshasa, Lubumbashi et Goma, colis vers 12 villes.",
        cols: [["Envoyer", [["send", "", "Envoyer un colis"], ["track", "", "Suivre un colis"], ["pricing", "", "Tarifs"], ["network", "#relais", "Points relais"]]], ["Entreprises", [["business", "", "Solutions"], ["business", "#api", "API et intégrations"], ["business", "#compte", "Ouvrir un compte"], ["couriers", "", "Devenir coursier"]]], ["Kimia", [["about", "", "À propos"], ["about", "#actualites", "Actualités"], ["help", "#reclamation", "Réclamations"], ["help", "#mentions", "Mentions légales"]]]],
        legal: "© 2026 Kimia Express SARL · RCCM CD/KNG/RCCM/19-B-04512 · Société fictive, démonstrateur", by: "Site réalisé par", photos: "Photos via Wikimedia Commons, recadrées et redimensionnées :", illus: "Illustrations : jeu d'images du projet Kimia, aux couleurs de la marque."
      },
      home: {
        eyebrow: "Kinshasa · Lubumbashi · Goma · 12 villes en RDC",
        h1: "Livré aujourd'hui à Kinshasa. En 48 heures à Goma.",
        lead: "Un coursier chez vous en 45 minutes, le prix affiché avant de réserver, le paiement par M-Pesa, Orange Money ou Airtel Money, et un SMS à chaque étape jusqu'à la signature.",
        live: { st: "En cours de livraison", eta: "Arrivée entre 11 h 20 et 11 h 40", who: "Junior K. · moto" },
        photoCap: "Livraison à moto, Kinshasa · Rahul Tilak, CC BY-SA 4.0",
        servicesEyebrow: "Services", servicesTitle: "Tout ce qui doit bouger, en ville et entre les villes", servicesLead: "Quatre services, une seule application, un seul numéro de suivi.",
        stepsEyebrow: "Comment ça marche", stepsTitle: "De la réservation à la signature",
        steps: [["Réservez", "Départ, arrivée, taille du colis : le prix s'affiche avant de confirmer. Sur le site, l'application ou WhatsApp."], ["Collecte", "Un coursier arrive en 45 minutes en moyenne, ou déposez le colis dans l'un de nos 28 points relais."], ["Suivez", "SMS ou WhatsApp à chaque étape, position du coursier en direct le jour de la livraison."], ["Livré", "Le destinataire signe sur le téléphone du coursier. Photo de preuve et reçu dans votre compte."]],
        netEyebrow: "Réseau", netTitle: "12 villes, trois façons d'y aller", netLead: "Motos en ville, camions sur la N1 vers le Kongo Central et le Kwilu, fret aérien depuis N'djili vers le Katanga, les Kivu, les Kasaï, la Tshopo et l'Équateur.", netMore: "Voir le réseau et les points relais", netCols: ["Ville", "Standard", "Express"],
        payEyebrow: "Paiement", payTitle: "Payez comme vous payez déjà", payLead: "Mobile money, carte ou espèces au coursier. L'expéditeur ou le destinataire peut régler, et le contre-remboursement est reversé en 24 heures.", payCap: "Point mobile money, photo d'illustration · Ndiwulira, CC BY-SA 4.0",
        bizEyebrow: "Entreprises", bizTitle: "Votre service de livraison, sans flotte à gérer", bizLead: "Boutiques en ligne, pharmacies, banques et distributeurs nous confient leurs livraisons, leur stock et leurs encaissements.", bizList: ["Jusqu'à 25 % de remise selon le volume", "Contre-remboursement reversé en 24 heures", "API, modules Shopify et WooCommerce", "Facture mensuelle et chargé de compte"], bizMore: "Solutions entreprises",
        drvEyebrow: "Coursiers", drvTitle: "Roulez avec Kimia", drvLead: "Payé à la course, versement chaque vendredi sur mobile money, casque, gilet et assurance fournis. Pas de moto ? Le programme Kimia Moto vous en loue une.", drvMore: "Devenir coursier", drvCap: "Motos-taxis à Goma · Izzobae, CC BY-SA 4.0",
        newsEyebrow: "Actualités", newsTitle: "Du nouveau chez Kimia", newsMore: "Toutes les actualités",
        appTitle: "Réservez et suivez depuis votre téléphone", appLead: "Partagez un lien de suivi en direct avec la personne qui reçoit le colis. Pas de smartphone ? Tout fonctionne aussi par SMS et par WhatsApp.", apps: ["Application Android", "Application iPhone", "WhatsApp +243 81 000 20 01"]
      },
      send: {
        h1: "Envoyer un colis", lead: "Quatre étapes, deux minutes. Le prix se calcule pendant que vous remplissez, et vous ne payez qu'à la confirmation.",
        steps: ["Trajet et colis", "Adresses", "Options", "Paiement"],
        from: "Départ", to: "Arrivée", city: "Ville", commune: "Commune",
        sizeT: "Taille du colis", dimsT: "Je connais le poids et les dimensions", weight: "Poids (kg)", L: "Longueur (cm)", W: "Largeur (cm)", H: "Hauteur (cm)", dimsHint: "Nous facturons le plus élevé du poids réel et du poids volumétrique (L × l × H ÷ 5 000).",
        value: "Valeur déclarée (FC)", valueHint: "Assurée sans frais jusqu'à 500 000 FC.", contents: "Contenu",
        contentsList: ["Documents", "Vêtements et textiles", "Téléphones et électronique", "Alimentaire sec", "Médicaments (avec facture de pharmacie)", "Pièces et outillage", "Cosmétiques", "Autre"],
        battery: "Le colis contient une batterie au lithium", batteryWarn: "Une batterie au lithium seule ne voyage pas en avion. Installée dans un appareil, elle est acceptée.",
        senderT: "Expéditeur", recipT: "Destinataire", name: "Nom complet", phone: "Téléphone", address: "Adresse", landmark: "Point de repère", landmarkPh: "Ex. : en face de l'église, portail bleu",
        pickupT: "Collecte", pickupDoor: "Un coursier vient chercher le colis", pickupRelay: "Je dépose le colis en point relais", dropT: "Livraison", dropDoor: "À l'adresse du destinataire", dropRelay: "Retrait en point relais", relay: "Point relais", relayDiscount: "Remise : 1 000 FC en ville, 5 000 FC entre les villes.",
        speedT: "Vitesse", stdSub: "En ville : 2 à 6 h. Intervilles : délai standard.", expSub: "En ville : moins de 2 h (+50 %). Intervilles : premier camion ou premier vol (+40 %).",
        whenT: "Collecte", asap: "Dès que possible (45 min en moyenne)", later: "Programmer", date: "Date", slot: "Créneau", slots: ["8 h – 10 h", "10 h – 12 h", "12 h – 14 h", "14 h – 16 h", "16 h – 18 h"],
        codT: "Contre-remboursement", codCheck: "Le coursier encaisse un montant auprès du destinataire", codAmount: "Montant à encaisser (FC)", codHint: "Reversé sous 24 heures. Frais : 2 %, minimum 1 000 FC.", notes: "Instructions pour le coursier",
        payT: "Moyen de paiement", payer: "Qui paie la livraison ?", payerSender: "L'expéditeur", payerRecip: "Le destinataire, à la livraison", mmPhone: "Numéro mobile money",
        cardNote: "Le paiement par carte se fait sur la page sécurisée de notre banque partenaire (simulé).", cashNote: "Réglez en espèces au coursier, lors de la collecte ou de la livraison selon le payeur.",
        summaryT: "Récapitulatif", back: "Retour", next: "Continuer", confirm: "Confirmer et payer",
        help: "Besoin d'aide ? WhatsApp +243 81 000 20 01, 7 j/7 de 6 h à 22 h.",
        packT: "Bien emballer", pack: ["Carton rigide, calé à l'intérieur : rien ne doit bouger quand on le secoue.", "Ruban adhésif en H sur le dessus et le dessous.", "Nom et téléphone du destinataire écrits sur le carton, en plus de l'étiquette.", "Liquides dans un sac fermé, puis dans le carton."],
        packCap: "Carton d'expédition · Bradsills, CC BY-SA 4.0"
      },
      track: {
        h1: "Suivre un colis", lead: "Entrez le numéro reçu par SMS. Il commence par KX.", label: "Numéro de suivi", btn: "Suivre",
        hint: "Numéros de démonstration :", demos: [["KX-2026-418207", "en transit"], ["KX-2026-305116", "en livraison"], ["KX-2026-221940", "livré"], ["KX-2026-190377", "tentative échouée"]],
        notifyT: "Recevoir les alertes", notifyLead: "Un message à chaque étape, sur le numéro de votre choix.", notifyPhone: "Téléphone", channel: "Canal", channels: ["SMS", "WhatsApp"], notifyBtn: "Activer les alertes",
        helpT: "Un problème avec un colis ?", helpLead: "Retard, colis abîmé, contre-remboursement non reçu : déposez une réclamation avec votre numéro de suivi. Réponse sous cinq jours ouvrés.", helpBtn: "Déposer une réclamation",
        faqT: "Questions sur le suivi", nightCap: "Kinshasa la nuit · MONUSCO Photos, CC BY-SA 2.0"
      },
      pricing: {
        h1: "Tarifs", lead: "Le prix dépend du trajet, de la taille du colis et de la vitesse. Il s'affiche avant la réservation et ne change pas ensuite, même dans les embouteillages.",
        estT: "Estimer un envoi", estLead: "Le même calcul que lors de la réservation.",
        urbanT: "En ville", urbanLead: "Kinshasa, Lubumbashi et Goma. Les communes sont réparties en zones ; le prix augmente de 3 000 FC par zone traversée.", urbanCols: ["Colis", "Même zone", "Zone voisine", "Zone 1 ↔ zone 3"], urbanNote: "Standard : 2 à 6 heures, avant 20 h pour toute collecte avant 16 h. Express, moins de 2 heures : +50 %.",
        zonesT: "Zones de Kinshasa", zoneNames: ["Zone 1 · centre", "Zone 2", "Zone 3 · périphérie"],
        interT: "Entre les villes", interLead: "Par la route vers le Kongo Central et le Kwilu, et entre deux villes d'une même région. Par avion depuis N'djili pour les autres destinations.", interCols: ["Colis", "Route", "Avion"], interNote: "Express (premier camion ou premier vol) : +40 %. Au-delà de 30 kg, fret sur devis jusqu'à 500 kg par envoi.",
        delaysT: "Délais depuis Kinshasa", delaysCols: ["Ville", "Province", "Transport", "Standard", "Express"],
        volT: "Poids volumétrique", volLead: "Un colis léger mais encombrant prend la place de plusieurs colis dans le camion ou l'avion. Nous facturons le plus élevé du poids réel et du poids volumétrique.", volBtn: "Calculer",
        optsT: "Options et frais",
        opts: [["Assurance", "Incluse jusqu'à 500 000 FC de valeur déclarée. Au-delà : 1 % de la valeur supplémentaire."], ["Contre-remboursement", "2 % du montant encaissé, minimum 1 000 FC. Reversé sous 24 heures."], ["Point relais", "Déposer ou retirer en point relais : –1 000 FC en ville, –5 000 FC entre les villes."], ["Attente", "10 minutes d'attente incluses, puis 1 000 FC par tranche de 10 minutes."], ["Nouvelle tentative", "Deuxième tentative gratuite le lendemain. Troisième tentative : 50 % du prix initial."], ["Retour à l'expéditeur", "Au prix de l'envoi initial. Garde gratuite cinq jours en point relais."]],
        payT: "Moyens de paiement", payLead: "Payé par l'expéditeur à la réservation, ou par le destinataire à la livraison.",
        docsT: "Documents", rateNote: "Prix TTC en francs congolais. Équivalent en dollars indicatif, calculé à 2 850 FC pour 1 USD.", trafficCap: "Embouteillage à Kinshasa · MONUSCO Photos, CC BY-SA 2.0"
      },
      business: {
        h1: "Entreprises", lead: "Livraison, stockage et encaissement pour les boutiques en ligne, pharmacies, banques et distributeurs. Un compte, une facture, un chargé de compte.", cta1: "Ouvrir un compte", cta2: "API et intégrations",
        solT: "Nos solutions", sol: [["Livraison e-commerce", "Collecte quotidienne dans votre boutique ou votre entrepôt, appel de confirmation avant expédition, contre-remboursement et retours gérés.", "boxes.jpg"], ["Stockage et préparation", "Kimia Stock : 2 500 m² au hub de Masina. Nous recevons votre marchandise, préparons chaque commande et l'expédions le jour même si elle arrive avant 14 h.", "warehouse.jpg"], ["Tournées programmées", "Banques, laboratoires, pharmacies : un coursier dédié, à heures fixes, pour les documents, les échantillons et le réassort.", "street.jpg"], ["Fret intervilles", "Palettes et colis lourds jusqu'à 500 kg, par la route ou par avion, avec rendez-vous de livraison à l'arrivée.", "plane.jpg"]],
        tiersT: "Remises selon le volume", tiersCols: ["Colis par mois", "Remise", "Facturation", "Reversement du contre-remboursement"],
        tiers: [["50 – 199", "10 %", "Mensuelle", "Sous 24 h"], ["200 – 999", "18 %", "Mensuelle", "Sous 24 h"], ["1 000 – 4 999", "25 %", "Mensuelle, à 15 jours", "Chaque jour à 18 h"], ["5 000 et plus", "Sur devis", "Sur contrat", "Chaque jour à 18 h"]],
        simT: "Estimer votre coût mensuel", simLead: "Un ordre de grandeur, calculé avec les prix publics et la remise de votre palier.", simOrders: "Commandes par mois", simUrban: "Part livrée en ville (%)", simCod: "Part en contre-remboursement (%)", simAvg: "Montant moyen encaissé (FC)",
        dashT: "Votre tableau de bord", dashLead: "Toutes vos commandes, leur statut, l'argent encaissé et les factures, en temps réel. Export Excel et accès pour votre équipe.",
        dash: { title: "Tableau de bord · Boutique Exemple", kpis: [["148", "commandes aujourd'hui"], ["131", "livrées"], ["14", "en cours"], ["3", "à reprogrammer"]], codLabel: "Contre-remboursement reversé demain", codValue: "4 820 000 FC", cols: ["N° de suivi", "Destination", "Statut", "Encaissé"],
          rows: [["KX-2026-512044", "Ngaliema", "delivered", "85 000 FC"], ["KX-2026-512051", "Lubumbashi", "transit", "—"], ["KX-2026-512063", "Limete", "out", "42 000 FC"], ["KX-2026-512070", "Masina", "failed", "—"], ["KX-2026-512078", "Goma", "delivered", "120 000 FC"]] },
        apiT: "API et intégrations", apiLead: "Créez des envois depuis votre site ou votre logiciel, recevez les statuts par webhook, imprimez les étiquettes en PDF.",
        integrations: [["API REST", "Création d'envoi, tarifs, suivi, étiquettes, webhooks. Environnement de test gratuit."], ["Shopify", "Application Kimia : prix au panier et envoi en un clic."], ["WooCommerce", "Extension WordPress, mêmes fonctions."], ["Import Excel", "Déposez votre fichier de commandes, nous créons les envois."]], apiNote: "Clé et numéros fictifs, pour illustration.",
        casesT: "Ils livrent avec Kimia", casesNote: "Exemples illustratifs.", cases: [["Boutique de mode en ligne, Kinshasa", "1 200 commandes par mois. L'appel de confirmation avant expédition a fait passer les refus à la livraison de 22 % à 9 %."], ["Réseau de neuf pharmacies", "Tournée programmée trois fois par jour entre les officines et le dépôt central de Limete."], ["Distributeur de téléphones", "Fret aérien Kinshasa – Goma chaque mardi, 180 kg en moyenne, remise contre signature."]],
        formT: "Ouvrir un compte entreprise", formLead: "Un conseiller vous rappelle sous un jour ouvré avec une proposition tarifaire.",
        form: { company: "Raison sociale", sector: "Secteur", sectors: ["Boutique en ligne", "Commerce de détail", "Pharmacie et santé", "Banque et assurance", "Distribution", "Restauration", "Administration ou ONG", "Autre"], city: "Ville", volume: "Colis par mois", volumes: ["Moins de 50", "50 à 199", "200 à 999", "1 000 à 4 999", "5 000 et plus"], needs: "Besoins", needsList: ["Livraison en ville", "Intervilles", "Contre-remboursement", "Stockage", "API"], contact: "Nom du contact", phone: "Téléphone", email: "E-mail", msg: "Précisions", send: "Envoyer la demande" },
        mallCap: "Kinshasa Mall · Kitangaza.1953, CC0", marketCap: "Supermarché à Kinshasa · Rahul Tilak, CC BY-SA 4.0"
      },
      network: {
        h1: "Réseau et points relais", lead: "12 villes, 28 agences et points relais, et un hub central à Masina, à dix minutes de l'aéroport de N'djili.",
        mapT: "Comment voyagent vos colis", mapLead: "Tout passe par le hub de Masina : tri de nuit, départ des camions à 5 h, embarquement sur les vols cargo du matin.", legend: { hub: "Hub central", city: "Ville desservie", road: "Route", air: "Avion depuis N'djili", regional: "Liaison régionale" }, schematic: "schéma, sans échelle",
        modesT: "Trois façons d'y aller", modes: [["Moto", "En ville : 620 coursiers à Kinshasa, 90 à Lubumbashi, 70 à Goma. La moto passe là où les voitures attendent."], ["Route", "Camion quotidien sur la N1 vers Matadi et Boma, trois fois par semaine vers Kikwit. Navettes Lubumbashi – Kolwezi et Goma – Bukavu."], ["Avion", "Fret sur les vols intérieurs depuis N'djili : chaque jour vers Lubumbashi et Goma, trois à cinq fois par semaine vers les autres villes. Barge pour les colis lourds, sur devis."]],
        citiesT: "Nos villes", tableT: "Délais et services", cols: ["Ville", "Province", "Depuis Kinshasa", "Standard", "Express", "Livraison à domicile", "Agences et relais"], modeNames: { hub: "Hub central", road: "Route", air: "Avion" }, urbanYes: "Toute la ville, à moto", urbanNo: "Centre-ville",
        relayT: "Trouver un point relais", relayLead: "Déposez, retirez et payez vos colis près de chez vous.", allCities: "Toutes les villes", search: "Commune, quartier ou nom", services: { depot: "Dépôt", retrait: "Retrait", paiement: "Paiement" }, kinds: { hub: "Hub", agence: "Agence Kimia", relais: "Point relais" },
        boulevardCap: "Boulevard du 30 juin, Kinshasa · Moyogo, CC BY-SA 3.0"
      },
      couriers: {
        h1: "Devenir coursier", lead: "Payé à chaque course, versement chaque vendredi, assurance et équipement fournis. Nous recrutons à Kinshasa, Lubumbashi et Goma.", cta1: "Postuler", cta2: "Autres emplois",
        whyT: "Pourquoi rouler avec Kimia", why: [["Un revenu clair", "2 200 FC en moyenne par course en ville, grille publiée dans l'application. Bonus de 25 000 FC par semaine au-delà de 95 % de livraisons à l'heure."], ["Payé chaque vendredi", "Versement sur M-Pesa, Orange Money ou Airtel Money. Aucun frais d'inscription, jamais."], ["Protégé", "Casque homologué, gilet, imperméable et assurance accident fournis. Formation sécurité routière de deux jours."], ["Libre", "Vous choisissez vos heures et vos zones. Pas de bonus de vitesse : nous payons la ponctualité, pas la prise de risque."]],
        earnT: "Estimer vos revenus", earnLead: "Exemple de calcul pour un coursier à Kinshasa. Les montants réels dépendent des courses acceptées.", perDay: "Courses par jour", daysWk: "Jours par semaine", moto: "Moto", motoOwn: "J'ai ma moto", motoRent: "Kimia Moto, 45 000 FC par semaine", bonus: "Je vise le bonus ponctualité",
        reqT: "Ce qu'il faut", req: ["18 ans ou plus", "Permis de conduire catégorie A", "Carte d'électeur ou passeport", "Smartphone Android", "Moto en bon état, ou programme Kimia Moto", "Attestation de bonne vie et mœurs"],
        motoT: "Kimia Moto", motoLead: "Pas de moto ? Nous vous en louons une, neuve et entretenue, 45 000 FC par semaine. Après 78 semaines, elle est à vous.",
        stepsT: "Comment ça se passe", steps: [["1. Candidature", "Formulaire ci-dessous ou au hub de Masina. Réponse par SMS sous 48 heures."], ["2. Entretien", "Vérification des documents, entretien et test de conduite au hub."], ["3. Formation", "Deux jours : sécurité routière, application, service client, contre-remboursement."], ["4. Première tournée", "Accompagné d'un chef d'équipe, puis vous roulez seul."]],
        jobsT: "Autres emplois", allCities: "Toutes les villes", allDepts: "Tous les services", closes: "Clôture",
        applyT: "Postuler", applyLead: "Chaque candidat reçoit un SMS sous 48 heures. Nous ne demandons jamais d'argent pour un recrutement : signalez toute demande au service client.",
        form: { name: "Nom complet", phone: "Téléphone", city: "Ville", cities: ["Kinshasa", "Lubumbashi", "Goma"], job: "Poste", moto: "Moto", motoOpts: ["J'ai ma moto", "Programme Kimia Moto", "Je ne sais pas encore"], licence: "Numéro de permis", cv: "CV ou photo du permis (PDF ou image)", msg: "Message", send: "Envoyer la candidature" },
        ridersCap: "Coursiers à moto, photo d'illustration prise à Nairobi · Rosiestep, CC BY-SA 4.0"
      },
      help: {
        h1: "Aide et contact", lead: "Questions fréquentes, réclamations, objets interdits et coordonnées de nos équipes.",
        faqT: "Questions fréquentes", search: "Rechercher une question", allCats: "Toutes les rubriques", cats: { send: "Envoyer", track: "Suivi", pay: "Paiement", biz: "Entreprises", claim: "Réclamations" },
        claimT: "Déposer une réclamation", claimLead: "Réponse sous cinq jours ouvrés. En cas de perte ou de dommage, indemnisation par mobile money sous dix jours ouvrés après accord.",
        claimForm: { tracking: "Numéro de suivi", type: "Motif", types: ["Retard", "Colis endommagé", "Colis perdu", "Contre-remboursement non reçu", "Comportement du coursier", "Facturation", "Autre"], name: "Nom", phone: "Téléphone", msg: "Que s'est-il passé ?", photo: "Photos (facultatif)", send: "Envoyer la réclamation" },
        prohibT: "Objets interdits ou réglementés", prohib: [["Interdits", ["Espèces et devises", "Armes, munitions et explosifs", "Carburant, gaz et produits inflammables", "Stupéfiants", "Animaux vivants", "Minerais, pierres et échantillons géologiques sans documents du CEEC"]], ["Acceptés sous conditions", ["Médicaments : avec facture de pharmacie", "Batteries au lithium : dans un appareil, jamais seules en avion", "Alimentaire frais : en ville uniquement", "Objets de plus de 5 000 000 FC : sur devis, assurance obligatoire"]]],
        contactT: "Nous joindre", points: [["Service client", "Réservations, suivi, réclamations", "phone", "email", "7 j/7 · 6 h – 22 h"], ["WhatsApp", "Réserver et suivre par message", "whatsapp", "email", "7 j/7 · 6 h – 22 h"], ["Entreprises", "Comptes, devis, API", "business", "businessEmail", "Lun–sam · 8 h – 18 h"], ["Coursiers", "Recrutement, versements", "couriers", "jobsEmail", "Lun–sam · 7 h – 17 h"], ["Réclamations", "Suivi des dossiers", "phone", "claimsEmail", "Lun–ven · 8 h – 17 h"], ["Presse", "Journalistes", "phone", "press", "Lun–ven · 9 h – 17 h"]],
        writeT: "Écrire à Kimia", form: { name: "Nom", email: "E-mail", subject: "Objet", subjects: ["Question sur un envoi", "Compte entreprise", "Devenir coursier", "Presse", "Autre"], msg: "Message", send: "Envoyer" },
        docsT: "Documents",
        legalT: "Mentions légales", legal: [["Dénomination", "Kimia Express SARL, société à responsabilité limitée au capital de 500 000 000 FC"], ["Siège", "12, avenue du Port, Gombe, Kinshasa"], ["RCCM", "CD/KNG/RCCM/19-B-04512"], ["Id. Nat.", "01-H5300-N84125P"], ["NIF", "A1907733K"], ["Autorisation", "Exploitation de services de courrier express, ministère des Postes, Télécommunications et Numérique (numéro fictif PTN/CE/2019/0147)"], ["Directrice de la publication", "Aline Mbala Kabongo"], ["Hébergement", "Serveurs situés à Kinshasa, copie de secours chiffrée hors du pays"], ["Données personnelles", "Noms, téléphones et adresses servent uniquement à la livraison et au service client. Ils sont conservés 12 mois après la livraison puis supprimés. Droit d'accès, de rectification et d'effacement à bonjour@kimia-express.cd, conformément à l'ordonnance-loi n° 23/010 du 13 mars 2023 portant Code du numérique."], ["Cookies", "Aucun traceur publicitaire. Stockage local limité à la langue, au consentement et aux envois de démonstration."]],
        gombeCap: "La Gombe, Kinshasa · ByaduniaEspoir, CC BY-SA 4.0"
      },
      about: {
        h1: "À propos", lead: "Kimia veut dire « paix » en lingala. Nous avons commencé en 2019 avec six motos et un numéro WhatsApp, pour que personne à Kinshasa n'ait plus à traverser la ville pour déposer un document.",
        missionT: "Notre mission", mission: "Rendre la livraison aussi simple qu'un appel : un prix clair, un coursier fiable, un colis qui arrive, partout en RDC.",
        figuresT: "Kimia en chiffres", historyT: "Notre histoire", leadersT: "Direction",
        commitT: "Nos engagements", commit: [["Coursiers", "Payés chaque semaine, assurés et équipés. Aucun bonus de vitesse, formation sécurité obligatoire."], ["Clients", "Prix affiché avant de réserver, preuve de livraison, réclamation traitée en cinq jours ouvrés."], ["Villes", "Trente motos électriques en test à la Gombe, tournées optimisées pour rouler moins."], ["Données", "Numéros et adresses utilisés pour la livraison seulement, conformément au Code du numérique."]],
        whyMotoT: "Pourquoi la moto", whyMoto: "À Kinshasa, une course de dix kilomètres peut prendre deux heures en voiture. À moto, un coursier formé la fait en quarante minutes, et peut livrer dans les quartiers où les rues ne sont pas goudronnées.",
        newsT: "Actualités", search: "Rechercher", allCat: "Toutes les rubriques", pressT: "Contact presse",
        aerialCap: "Kinshasa depuis le 16e étage · Irene2005, CC BY 2.0", trafficCap: "Embouteillage à Kinshasa · MONUSCO Photos, CC BY-SA 2.0"
      }
    },
    en: {
      demoBar: "IK Digital Solutions demonstrator · Kimia Express SARL is a fictitious company. Prices, parcels, people and documents are illustrative; bookings, payments and SMS are simulated.",
      back: "← Back to portfolio", skip: "Skip to content", menu: "Menu", navLabel: "Main navigation",
      util: { care: "Customer service, 7 days", about: "About", jobs: "Careers" },
      nav: [["pricing", "Pricing"], ["business", "Business"], ["network", "Network & relay points"], ["couriers", "Become a courier"], ["help", "Help"]],
      cta: { track: "Track", send: "Send a parcel" },
      illustrative: "Illustrative figures: fictitious company created for demonstration.",
      consent: { text: "This site uses local storage to remember your language, preferences and demo shipments. No advertising trackers. Under the Digital Code you may accept or decline.", yes: "Accept", no: "Decline", more: "Data policy" },
      common: { download: "Download", from: "From", book: "Book", more: "Learn more", home: "Home" },
      quick: { tabQuote: "Get a price", tabTrack: "Track a parcel", from: "From", to: "To", commune: "Commune", size: "Parcel", speed: "Speed", std: "Standard", exp: "Express", price: "Estimated price", book: "Book a pickup", trackLabel: "Tracking number", trackBtn: "Track", tryHint: "Try KX-2026-418207 or KX-2026-305116.", note: "All taxes included, no hidden fees. Pay when you confirm." },
      footer: {
        about: "Express delivery and logistics in the DRC since 2019: motorbike couriers in Kinshasa, Lubumbashi and Goma, parcels to 12 cities.",
        cols: [["Send", [["send", "", "Send a parcel"], ["track", "", "Track a parcel"], ["pricing", "", "Pricing"], ["network", "#relais", "Relay points"]]], ["Business", [["business", "", "Solutions"], ["business", "#api", "API and integrations"], ["business", "#compte", "Open an account"], ["couriers", "", "Become a courier"]]], ["Kimia", [["about", "", "About"], ["about", "#actualites", "News"], ["help", "#reclamation", "Claims"], ["help", "#mentions", "Legal notice"]]]],
        legal: "© 2026 Kimia Express SARL · RCCM CD/KNG/RCCM/19-B-04512 · Fictitious company, demonstrator", by: "Site built by", photos: "Photos via Wikimedia Commons, cropped and resized:", illus: "Illustrations: Kimia project image set, in brand colours."
      },
      home: {
        eyebrow: "Kinshasa · Lubumbashi · Goma · 12 cities in the DRC",
        h1: "Delivered today in Kinshasa. Within 48 hours in Goma.",
        lead: "A courier at your door in 45 minutes, the price shown before you book, payment by M-Pesa, Orange Money or Airtel Money, and an SMS at every step until signature.",
        live: { st: "Out for delivery", eta: "Arriving 11.20 – 11.40 am", who: "Junior K. · motorbike" },
        photoCap: "Motorbike delivery, Kinshasa · Rahul Tilak, CC BY-SA 4.0",
        servicesEyebrow: "Services", servicesTitle: "Everything that needs to move, across town and between cities", servicesLead: "Four services, one app, one tracking number.",
        stepsEyebrow: "How it works", stepsTitle: "From booking to signature",
        steps: [["Book", "Origin, destination, parcel size: the price appears before you confirm. On the website, the app or WhatsApp."], ["Pickup", "A courier arrives in 45 minutes on average, or drop the parcel at one of our 28 relay points."], ["Track", "SMS or WhatsApp at every step, the courier's live position on delivery day."], ["Delivered", "The recipient signs on the courier's phone. Proof photo and receipt in your account."]],
        netEyebrow: "Network", netTitle: "12 cities, three ways to get there", netLead: "Motorbikes in town, trucks on the N1 to Kongo Central and Kwilu, air freight from N'djili to Katanga, the Kivus, the Kasaïs, Tshopo and Équateur.", netMore: "See the network and relay points", netCols: ["City", "Standard", "Express"],
        payEyebrow: "Payment", payTitle: "Pay the way you already pay", payLead: "Mobile money, card or cash to the courier. Either the sender or the recipient can pay, and cash on delivery is paid out within 24 hours.", payCap: "Mobile money outlet, illustrative photo · Ndiwulira, CC BY-SA 4.0",
        bizEyebrow: "Business", bizTitle: "Your delivery service, without a fleet to run", bizLead: "Online shops, pharmacies, banks and distributors trust us with their deliveries, their stock and their collections.", bizList: ["Up to 25% off depending on volume", "Cash on delivery paid out within 24 hours", "API, Shopify and WooCommerce plugins", "Monthly invoice and account manager"], bizMore: "Business solutions",
        drvEyebrow: "Couriers", drvTitle: "Ride with Kimia", drvLead: "Paid per delivery, paid out every Friday by mobile money, helmet, vest and insurance provided. No motorbike? The Kimia Moto programme rents you one.", drvMore: "Become a courier", drvCap: "Motorbike taxis in Goma · Izzobae, CC BY-SA 4.0",
        newsEyebrow: "News", newsTitle: "What's new at Kimia", newsMore: "All news",
        appTitle: "Book and track from your phone", appLead: "Share a live tracking link with the person receiving the parcel. No smartphone? Everything also works by SMS and WhatsApp.", apps: ["Android app", "iPhone app", "WhatsApp +243 81 000 20 01"]
      },
      send: {
        h1: "Send a parcel", lead: "Four steps, two minutes. The price is calculated as you fill in the form, and you only pay when you confirm.",
        steps: ["Route and parcel", "Addresses", "Options", "Payment"],
        from: "From", to: "To", city: "City", commune: "Commune",
        sizeT: "Parcel size", dimsT: "I know the weight and dimensions", weight: "Weight (kg)", L: "Length (cm)", W: "Width (cm)", H: "Height (cm)", dimsHint: "We charge the higher of actual weight and volumetric weight (L × W × H ÷ 5,000).",
        value: "Declared value (FC)", valueHint: "Insured free of charge up to 500,000 FC.", contents: "Contents",
        contentsList: ["Documents", "Clothing and textiles", "Phones and electronics", "Dry food", "Medicines (with pharmacy receipt)", "Parts and tools", "Cosmetics", "Other"],
        battery: "The parcel contains a lithium battery", batteryWarn: "A lithium battery on its own cannot fly. Fitted inside a device, it is accepted.",
        senderT: "Sender", recipT: "Recipient", name: "Full name", phone: "Phone", address: "Address", landmark: "Landmark", landmarkPh: "E.g. opposite the church, blue gate",
        pickupT: "Pickup", pickupDoor: "A courier collects the parcel", pickupRelay: "I drop the parcel at a relay point", dropT: "Delivery", dropDoor: "To the recipient's address", dropRelay: "Collection at a relay point", relay: "Relay point", relayDiscount: "Discount: 1,000 FC within a city, 5,000 FC between cities.",
        speedT: "Speed", stdSub: "In town: 2 to 6 h. Intercity: standard time.", expSub: "In town: under 2 h (+50%). Intercity: first truck or first flight (+40%).",
        whenT: "Pickup", asap: "As soon as possible (45 min on average)", later: "Schedule", date: "Date", slot: "Time slot", slots: ["8 – 10 am", "10 am – 12 pm", "12 – 2 pm", "2 – 4 pm", "4 – 6 pm"],
        codT: "Cash on delivery", codCheck: "The courier collects an amount from the recipient", codAmount: "Amount to collect (FC)", codHint: "Paid out within 24 hours. Fee: 2%, minimum 1,000 FC.", notes: "Instructions for the courier",
        payT: "Payment method", payer: "Who pays for delivery?", payerSender: "The sender", payerRecip: "The recipient, on delivery", mmPhone: "Mobile money number",
        cardNote: "Card payment takes place on our partner bank's secure page (simulated).", cashNote: "Pay the courier in cash, at pickup or on delivery depending on who pays.",
        summaryT: "Summary", back: "Back", next: "Continue", confirm: "Confirm and pay",
        help: "Need help? WhatsApp +243 81 000 20 01, daily from 6 am to 10 pm.",
        packT: "Pack it well", pack: ["A rigid box, padded inside: nothing should move when you shake it.", "Tape in an H on the top and bottom.", "Recipient's name and phone written on the box as well as the label.", "Liquids in a sealed bag, then in the box."],
        packCap: "Shipping carton · Bradsills, CC BY-SA 4.0"
      },
      track: {
        h1: "Track a parcel", lead: "Enter the number you received by SMS. It starts with KX.", label: "Tracking number", btn: "Track",
        hint: "Demo numbers:", demos: [["KX-2026-418207", "in transit"], ["KX-2026-305116", "out for delivery"], ["KX-2026-221940", "delivered"], ["KX-2026-190377", "failed attempt"]],
        notifyT: "Get alerts", notifyLead: "A message at every step, on the number of your choice.", notifyPhone: "Phone", channel: "Channel", channels: ["SMS", "WhatsApp"], notifyBtn: "Turn on alerts",
        helpT: "A problem with a parcel?", helpLead: "Delay, damaged parcel, cash on delivery not received: file a claim with your tracking number. Reply within five working days.", helpBtn: "File a claim",
        faqT: "Tracking questions", nightCap: "Kinshasa at night · MONUSCO Photos, CC BY-SA 2.0"
      },
      pricing: {
        h1: "Pricing", lead: "The price depends on the route, the parcel size and the speed. It is shown before you book and does not change afterwards, even in traffic jams.",
        estT: "Get a price", estLead: "The same calculation as at booking.",
        urbanT: "Within a city", urbanLead: "Kinshasa, Lubumbashi and Goma. Communes are grouped into zones; the price rises by 3,000 FC for each zone crossed.", urbanCols: ["Parcel", "Same zone", "Next zone", "Zone 1 ↔ zone 3"], urbanNote: "Standard: 2 to 6 hours, before 8 pm for any pickup before 4 pm. Express, under 2 hours: +50%.",
        zonesT: "Kinshasa zones", zoneNames: ["Zone 1 · centre", "Zone 2", "Zone 3 · outskirts"],
        interT: "Between cities", interLead: "By road to Kongo Central and Kwilu, and between two cities in the same region. By air from N'djili for other destinations.", interCols: ["Parcel", "Road", "Air"], interNote: "Express (first truck or first flight): +40%. Over 30 kg, freight on quotation up to 500 kg per shipment.",
        delaysT: "Delivery times from Kinshasa", delaysCols: ["City", "Province", "Transport", "Standard", "Express"],
        volT: "Volumetric weight", volLead: "A light but bulky parcel takes the space of several parcels in the truck or plane. We charge the higher of actual and volumetric weight.", volBtn: "Calculate",
        optsT: "Options and fees",
        opts: [["Insurance", "Included up to 500,000 FC declared value. Above that: 1% of the additional value."], ["Cash on delivery", "2% of the amount collected, minimum 1,000 FC. Paid out within 24 hours."], ["Relay point", "Drop off or collect at a relay point: –1,000 FC within a city, –5,000 FC between cities."], ["Waiting", "10 minutes of waiting included, then 1,000 FC per 10 minutes."], ["New attempt", "Second attempt free the next day. Third attempt: 50% of the original price."], ["Return to sender", "At the original shipment price. Kept free for five days at a relay point."]],
        payT: "Payment methods", payLead: "Paid by the sender at booking, or by the recipient on delivery.",
        docsT: "Documents", rateNote: "Prices in Congolese francs, all taxes included. Dollar equivalent for information, at 2,850 FC to 1 USD.", trafficCap: "Traffic jam in Kinshasa · MONUSCO Photos, CC BY-SA 2.0"
      },
      business: {
        h1: "Business", lead: "Delivery, storage and collections for online shops, pharmacies, banks and distributors. One account, one invoice, one account manager.", cta1: "Open an account", cta2: "API and integrations",
        solT: "Our solutions", sol: [["E-commerce delivery", "Daily pickup at your shop or warehouse, confirmation call before dispatch, cash on delivery and returns handled.", "boxes.jpg"], ["Storage and fulfilment", "Kimia Stock: 2,500 m² at the Masina hub. We receive your goods, pack each order and ship it the same day if it arrives before 2 pm.", "warehouse.jpg"], ["Scheduled rounds", "Banks, laboratories, pharmacies: a dedicated courier at fixed times for documents, samples and restocking.", "street.jpg"], ["Intercity freight", "Pallets and heavy parcels up to 500 kg, by road or air, with a delivery appointment on arrival.", "plane.jpg"]],
        tiersT: "Volume discounts", tiersCols: ["Parcels per month", "Discount", "Billing", "Cash-on-delivery payout"],
        tiers: [["50 – 199", "10%", "Monthly", "Within 24 h"], ["200 – 999", "18%", "Monthly", "Within 24 h"], ["1,000 – 4,999", "25%", "Monthly, 15 days", "Daily at 6 pm"], ["5,000 and more", "On quotation", "By contract", "Daily at 6 pm"]],
        simT: "Estimate your monthly cost", simLead: "An order of magnitude, using public prices and your tier's discount.", simOrders: "Orders per month", simUrban: "Share delivered in town (%)", simCod: "Share with cash on delivery (%)", simAvg: "Average amount collected (FC)",
        dashT: "Your dashboard", dashLead: "All your orders, their status, the cash collected and invoices, in real time. Excel export and access for your team.",
        dash: { title: "Dashboard · Example Shop", kpis: [["148", "orders today"], ["131", "delivered"], ["14", "in progress"], ["3", "to reschedule"]], codLabel: "Cash on delivery paid out tomorrow", codValue: "4,820,000 FC", cols: ["Tracking no.", "Destination", "Status", "Collected"],
          rows: [["KX-2026-512044", "Ngaliema", "delivered", "85,000 FC"], ["KX-2026-512051", "Lubumbashi", "transit", "—"], ["KX-2026-512063", "Limete", "out", "42,000 FC"], ["KX-2026-512070", "Masina", "failed", "—"], ["KX-2026-512078", "Goma", "delivered", "120,000 FC"]] },
        apiT: "API and integrations", apiLead: "Create shipments from your website or software, receive status updates by webhook, print labels as PDF.",
        integrations: [["REST API", "Shipment creation, rates, tracking, labels, webhooks. Free test environment."], ["Shopify", "Kimia app: prices at checkout and one-click shipping."], ["WooCommerce", "WordPress extension, same features."], ["Excel import", "Upload your order file, we create the shipments."]], apiNote: "Fictitious key and numbers, for illustration.",
        casesT: "They deliver with Kimia", casesNote: "Illustrative examples.", cases: [["Online fashion shop, Kinshasa", "1,200 orders a month. The confirmation call before dispatch cut refusals on delivery from 22% to 9%."], ["Network of nine pharmacies", "Scheduled round three times a day between the pharmacies and the central Limete store."], ["Phone distributor", "Air freight Kinshasa – Goma every Tuesday, 180 kg on average, handed over against signature."]],
        formT: "Open a business account", formLead: "An adviser calls you back within one working day with a price proposal.",
        form: { company: "Company name", sector: "Sector", sectors: ["Online shop", "Retail", "Pharmacy and health", "Banking and insurance", "Distribution", "Food service", "Government or NGO", "Other"], city: "City", volume: "Parcels per month", volumes: ["Under 50", "50 to 199", "200 to 999", "1,000 to 4,999", "5,000 and more"], needs: "Needs", needsList: ["City delivery", "Intercity", "Cash on delivery", "Storage", "API"], contact: "Contact name", phone: "Phone", email: "E-mail", msg: "Details", send: "Send request" },
        mallCap: "Kinshasa Mall · Kitangaza.1953, CC0", marketCap: "Supermarket in Kinshasa · Rahul Tilak, CC BY-SA 4.0"
      },
      network: {
        h1: "Network and relay points", lead: "12 cities, 28 offices and relay points, and a central hub in Masina, ten minutes from N'djili Airport.",
        mapT: "How your parcels travel", mapLead: "Everything goes through the Masina hub: night sorting, trucks leaving at 5 am, loading onto the morning cargo flights.", legend: { hub: "Central hub", city: "City served", road: "Road", air: "Air from N'djili", regional: "Regional link" }, schematic: "schematic, not to scale",
        modesT: "Three ways to get there", modes: [["Motorbike", "In town: 620 couriers in Kinshasa, 90 in Lubumbashi, 70 in Goma. A motorbike gets through where cars wait."], ["Road", "Daily truck on the N1 to Matadi and Boma, three times a week to Kikwit. Shuttles Lubumbashi – Kolwezi and Goma – Bukavu."], ["Air", "Freight on domestic flights from N'djili: daily to Lubumbashi and Goma, three to five times a week to other cities. Barge for heavy parcels, on quotation."]],
        citiesT: "Our cities", tableT: "Delivery times and services", cols: ["City", "Province", "From Kinshasa", "Standard", "Express", "Home delivery", "Offices and relays"], modeNames: { hub: "Central hub", road: "Road", air: "Air" }, urbanYes: "Whole city, by motorbike", urbanNo: "City centre",
        relayT: "Find a relay point", relayLead: "Drop off, collect and pay for parcels near you.", allCities: "All cities", search: "Commune, district or name", services: { depot: "Drop-off", retrait: "Collection", paiement: "Payment" }, kinds: { hub: "Hub", agence: "Kimia office", relais: "Relay point" },
        boulevardCap: "Boulevard du 30 juin, Kinshasa · Moyogo, CC BY-SA 3.0"
      },
      couriers: {
        h1: "Become a courier", lead: "Paid for every delivery, paid out every Friday, insurance and equipment provided. We are recruiting in Kinshasa, Lubumbashi and Goma.", cta1: "Apply", cta2: "Other jobs",
        whyT: "Why ride with Kimia", why: [["Clear income", "2,200 FC on average per delivery in town, rates published in the app. Bonus of 25,000 FC a week above 95% on-time deliveries."], ["Paid every Friday", "Paid out via M-Pesa, Orange Money or Airtel Money. No sign-up fee, ever."], ["Protected", "Approved helmet, vest, rain gear and accident insurance provided. Two-day road safety course."], ["Free", "You choose your hours and zones. No speed bonus: we pay for punctuality, not risk-taking."]],
        earnT: "Estimate your income", earnLead: "Example calculation for a courier in Kinshasa. Actual amounts depend on the deliveries you accept.", perDay: "Deliveries per day", daysWk: "Days per week", moto: "Motorbike", motoOwn: "I have my own", motoRent: "Kimia Moto, 45,000 FC a week", bonus: "I aim for the punctuality bonus",
        reqT: "What you need", req: ["18 or older", "Category A driving licence", "Voter card or passport", "Android smartphone", "Motorbike in good condition, or the Kimia Moto programme", "Certificate of good conduct"],
        motoT: "Kimia Moto", motoLead: "No motorbike? We rent you one, new and serviced, for 45,000 FC a week. After 78 weeks, it is yours.",
        stepsT: "How it works", steps: [["1. Apply", "Form below or at the Masina hub. Reply by SMS within 48 hours."], ["2. Interview", "Document check, interview and riding test at the hub."], ["3. Training", "Two days: road safety, the app, customer service, cash on delivery."], ["4. First round", "With a team leader, then you ride on your own."]],
        jobsT: "Other jobs", allCities: "All cities", allDepts: "All departments", closes: "Closes",
        applyT: "Apply", applyLead: "Every applicant receives an SMS within 48 hours. We never ask for money to hire anyone: report any such request to customer service.",
        form: { name: "Full name", phone: "Phone", city: "City", cities: ["Kinshasa", "Lubumbashi", "Goma"], job: "Position", moto: "Motorbike", motoOpts: ["I have my own", "Kimia Moto programme", "Not sure yet"], licence: "Licence number", cv: "CV or photo of licence (PDF or image)", msg: "Message", send: "Send application" },
        ridersCap: "Motorbike couriers, illustrative photo taken in Nairobi · Rosiestep, CC BY-SA 4.0"
      },
      help: {
        h1: "Help and contact", lead: "Frequent questions, claims, prohibited items and how to reach our teams.",
        faqT: "Frequent questions", search: "Search a question", allCats: "All topics", cats: { send: "Sending", track: "Tracking", pay: "Payment", biz: "Business", claim: "Claims" },
        claimT: "File a claim", claimLead: "Reply within five working days. For loss or damage, compensation by mobile money within ten working days of agreement.",
        claimForm: { tracking: "Tracking number", type: "Reason", types: ["Delay", "Damaged parcel", "Lost parcel", "Cash on delivery not received", "Courier behaviour", "Billing", "Other"], name: "Name", phone: "Phone", msg: "What happened?", photo: "Photos (optional)", send: "Send claim" },
        prohibT: "Prohibited and restricted items", prohib: [["Prohibited", ["Cash and foreign currency", "Weapons, ammunition and explosives", "Fuel, gas and flammable goods", "Narcotics", "Live animals", "Minerals, stones and geological samples without CEEC documents"]], ["Accepted with conditions", ["Medicines: with pharmacy receipt", "Lithium batteries: inside a device, never alone by air", "Fresh food: within a city only", "Items worth over 5,000,000 FC: on quotation, insurance required"]]],
        contactT: "Reach us", points: [["Customer service", "Bookings, tracking, claims", "phone", "email", "Daily · 6 am – 10 pm"], ["WhatsApp", "Book and track by message", "whatsapp", "email", "Daily · 6 am – 10 pm"], ["Business", "Accounts, quotes, API", "business", "businessEmail", "Mon–Sat · 8 am – 6 pm"], ["Couriers", "Recruitment, payouts", "couriers", "jobsEmail", "Mon–Sat · 7 am – 5 pm"], ["Claims", "Case follow-up", "phone", "claimsEmail", "Mon–Fri · 8 am – 5 pm"], ["Press", "Journalists", "phone", "press", "Mon–Fri · 9 am – 5 pm"]],
        writeT: "Write to Kimia", form: { name: "Name", email: "E-mail", subject: "Subject", subjects: ["Question about a shipment", "Business account", "Becoming a courier", "Press", "Other"], msg: "Message", send: "Send" },
        docsT: "Documents",
        legalT: "Legal notice", legal: [["Company", "Kimia Express SARL, private limited company with a capital of 500,000,000 FC"], ["Registered office", "12 avenue du Port, Gombe, Kinshasa"], ["RCCM", "CD/KNG/RCCM/19-B-04512"], ["Nat. ID", "01-H5300-N84125P"], ["NIF", "A1907733K"], ["Licence", "Express courier services, Ministry of Posts, Telecommunications and Digital (fictitious number PTN/CE/2019/0147)"], ["Publication director", "Aline Mbala Kabongo"], ["Hosting", "Servers located in Kinshasa, encrypted backup copy outside the country"], ["Personal data", "Names, phone numbers and addresses are used only for delivery and customer service. They are kept 12 months after delivery, then deleted. Right of access, correction and erasure at bonjour@kimia-express.cd, under ordinance-law no. 23/010 of 13 March 2023 on the Digital Code."], ["Cookies", "No advertising trackers. Local storage limited to language, consent and demo shipments."]],
        gombeCap: "La Gombe, Kinshasa · ByaduniaEspoir, CC BY-SA 4.0"
      },
      about: {
        h1: "About", lead: "Kimia means “peace” in Lingala. We started in 2019 with six motorbikes and a WhatsApp number, so that nobody in Kinshasa would have to cross the city to drop off a document again.",
        missionT: "Our mission", mission: "Make delivery as simple as a phone call: a clear price, a reliable courier, a parcel that arrives, anywhere in the DRC.",
        figuresT: "Kimia in figures", historyT: "Our story", leadersT: "Leadership",
        commitT: "Our commitments", commit: [["Couriers", "Paid every week, insured and equipped. No speed bonus, mandatory safety training."], ["Customers", "Price shown before booking, proof of delivery, claims handled within five working days."], ["Cities", "Thirty electric motorbikes on trial in Gombe, optimised rounds to ride less."], ["Data", "Phone numbers and addresses used for delivery only, under the Digital Code."]],
        whyMotoT: "Why motorbikes", whyMoto: "In Kinshasa a ten-kilometre trip can take two hours by car. On a motorbike, a trained courier does it in forty minutes, and can deliver in districts where the streets are not paved.",
        newsT: "News", search: "Search", allCat: "All topics", pressT: "Press contact",
        aerialCap: "Kinshasa from the 16th floor · Irene2005, CC BY 2.0", trafficCap: "Traffic jam in Kinshasa · MONUSCO Photos, CC BY-SA 2.0"
      }
    }
  },

  /* ---------- strings used by site.js (written to data.js) ---------- */
  js: {
    fr: {
      locale: "fr-FR", usd: "≈ {n} USD",
      modes: { urban: "En ville", road: "Route", air: "Avion" },
      today: "aujourd'hui", sameDayRoad: "le jour même (remis avant 8 h)", urbanStd: "2 à 6 heures", urbanExp: "moins de 2 heures",
      etaDate: "Livraison estimée {d}", noUrban: "La livraison en ville est disponible à Kinshasa, Lubumbashi et Goma.", tooHeavy: "Au-delà de 30 kg : fret sur devis.",
      lines: { base: "Transport", zone: "Supplément de zone", express: "Express", relay: "Remise point relais", insurance: "Assurance complémentaire", cod: "Frais de contre-remboursement", total: "Total" },
      billed: "Poids facturé : {w} kg · {s}", volOut: "Poids volumétrique : {v} kg. Poids facturé : {b} kg, soit {s}.", volOver: "Poids facturé : {b} kg. Au-delà de 30 kg, fret sur devis.",
      required: "Complétez les champs signalés.", badPhone: "Numéro invalide. Exemple : +243 81 234 56 78",
      payPush: "Demande de paiement envoyée au {p} via {m}. Validez avec votre code PIN.", payCard: "Redirection vers la page de paiement sécurisée…", payCash: "Enregistrement de la réservation…",
      okTitle: "Envoi confirmé", okTrack: "Numéro de suivi", okSms: "SMS envoyé à l'expéditeur et au destinataire (simulé).",
      sms: "Kimia Express : envoi {id} confirme. {route}. Collecte {when}. Montant {price}. Suivi sur kimia-express.cd",
      whenAsap: "dans 45 min environ", whenLater: "le {d}, {s}", pickupRelay: "dépôt au point relais {r}",
      printLabel: "Imprimer l'étiquette", trackIt: "Suivre ce colis", newOne: "Nouvel envoi", labelFrom: "De", labelTo: "À",
      trackBad: "Le numéro doit ressembler à KX-2026-000000.", trackNone: "Aucun colis avec ce numéro dans la démonstration. Essayez KX-2026-418207, ou réservez un envoi pour obtenir un numéro.",
      stages: ["Réservé", "Collecté", "En transit", "En livraison", "Livré"],
      status: { booked: "Réservé", transit: "En transit", out: "En cours de livraison", delivered: "Livré", failed: "Tentative échouée" },
      evBooked: "Envoi réservé ({m})", evPickup: "Collecte prévue {w}", evRelay: "À déposer au point relais {r}", nextStd: "Livraison estimée {d}",
      route: "Trajet", parcel: "Colis", mode: "Transport", speed: "Vitesse", speeds: { std: "Standard", exp: "Express" }, weight: "Poids",
      share: "Copier le lien de suivi", copied: "Lien de suivi copié.", courier: "Votre coursier",
      resT: "Modifier la livraison", resDate: "Nouvelle date", resBtn: "Reprogrammer", relayBtn: "Livrer en point relais", resOk: "Nouvelle tentative programmée le {d}. SMS envoyé au destinataire (simulé).", relayOk: "Colis redirigé vers {r}. Retrait possible dès demain (simulé).",
      proofT: "Preuve de livraison", receivedBy: "Reçu par", at: "Le", codCollected: "Montant encaissé", payout: "Reversement",
      notifyOk: "Alertes activées sur le {p} par {c} (simulé).", formOk: "Message reçu. Nous répondons sous un jour ouvré (simulé).",
      claimOk: "Réclamation enregistrée sous la référence {r}. Réponse sous cinq jours ouvrés ; un SMS de confirmation vous est envoyé (simulé).",
      bizOk: "Demande enregistrée sous la référence {r}. Un conseiller vous rappelle sous un jour ouvré (simulé).",
      applyOk: "Candidature reçue sous la référence {r}. Un SMS vous est envoyé sous 48 heures (simulé).",
      docTitle: "Document fourni par la société", docBody: "Sur le site en production, ce lien ouvre le PDF publié par Kimia Express. Dans cette démonstration, le document n'existe pas encore.", close: "Fermer",
      noRelay: "Aucun point relais ne correspond.", noFaq: "Aucune question ne correspond. Écrivez-nous sur WhatsApp au +243 81 000 20 01.", noJobs: "Aucun poste ne correspond à ces filtres.", noNews: "Aucune actualité ne correspond.",
      earn: { gross: "Courses ({n} par mois)", fuel: "Carburant estimé", rent: "Location Kimia Moto", bonus: "Bonus ponctualité", net: "Revenu net estimé par mois" },
      sim: { base: "Livraisons au prix public", discount: "Remise volume ({p})", cod: "Frais de contre-remboursement", total: "Coût mensuel estimé", per: "soit {n} par commande", none: "aucune" },
      dashStatus: { delivered: "Livré", transit: "En transit", out: "En livraison", failed: "À reprogrammer" },
      invalidTracking: "Numéro de suivi invalide (format KX-2026-000000)."
    },
    en: {
      locale: "en-GB", usd: "≈ USD {n}",
      modes: { urban: "In town", road: "Road", air: "Air" },
      today: "today", sameDayRoad: "same day (handed in before 8 am)", urbanStd: "2 to 6 hours", urbanExp: "under 2 hours",
      etaDate: "Estimated delivery {d}", noUrban: "City delivery is available in Kinshasa, Lubumbashi and Goma.", tooHeavy: "Over 30 kg: freight on quotation.",
      lines: { base: "Transport", zone: "Zone supplement", express: "Express", relay: "Relay point discount", insurance: "Extra insurance", cod: "Cash-on-delivery fee", total: "Total" },
      billed: "Charged weight: {w} kg · {s}", volOut: "Volumetric weight: {v} kg. Charged weight: {b} kg, which is a {s}.", volOver: "Charged weight: {b} kg. Over 30 kg, freight on quotation.",
      required: "Please complete the highlighted fields.", badPhone: "Invalid number. Example: +243 81 234 56 78",
      payPush: "Payment request sent to {p} via {m}. Approve it with your PIN.", payCard: "Redirecting to the secure payment page…", payCash: "Saving your booking…",
      okTitle: "Shipment confirmed", okTrack: "Tracking number", okSms: "SMS sent to the sender and the recipient (simulated).",
      sms: "Kimia Express: shipment {id} confirmed. {route}. Pickup {when}. Amount {price}. Track at kimia-express.cd",
      whenAsap: "in about 45 min", whenLater: "on {d}, {s}", pickupRelay: "drop-off at relay point {r}",
      printLabel: "Print label", trackIt: "Track this parcel", newOne: "New shipment", labelFrom: "From", labelTo: "To",
      trackBad: "The number should look like KX-2026-000000.", trackNone: "No parcel with this number in the demonstration. Try KX-2026-418207, or book a shipment to get a number.",
      stages: ["Booked", "Picked up", "In transit", "Out for delivery", "Delivered"],
      status: { booked: "Booked", transit: "In transit", out: "Out for delivery", delivered: "Delivered", failed: "Failed attempt" },
      evBooked: "Shipment booked ({m})", evPickup: "Pickup planned {w}", evRelay: "To be dropped at relay point {r}", nextStd: "Estimated delivery {d}",
      route: "Route", parcel: "Parcel", mode: "Transport", speed: "Speed", speeds: { std: "Standard", exp: "Express" }, weight: "Weight",
      share: "Copy tracking link", copied: "Tracking link copied.", courier: "Your courier",
      resT: "Change delivery", resDate: "New date", resBtn: "Reschedule", relayBtn: "Deliver to a relay point", resOk: "New attempt scheduled for {d}. SMS sent to the recipient (simulated).", relayOk: "Parcel redirected to {r}. Ready for collection from tomorrow (simulated).",
      proofT: "Proof of delivery", receivedBy: "Received by", at: "On", codCollected: "Amount collected", payout: "Payout",
      notifyOk: "Alerts turned on for {p} by {c} (simulated).", formOk: "Message received. We reply within one working day (simulated).",
      claimOk: "Claim recorded under reference {r}. Reply within five working days; a confirmation SMS is sent to you (simulated).",
      bizOk: "Request recorded under reference {r}. An adviser calls you back within one working day (simulated).",
      applyOk: "Application received under reference {r}. You will get an SMS within 48 hours (simulated).",
      docTitle: "Document provided by the company", docBody: "On the production site this link opens the PDF published by Kimia Express. In this demonstration the document does not exist yet.", close: "Close",
      noRelay: "No relay point matches.", noFaq: "No question matches. Message us on WhatsApp at +243 81 000 20 01.", noJobs: "No position matches these filters.", noNews: "No news item matches.",
      earn: { gross: "Deliveries ({n} a month)", fuel: "Estimated fuel", rent: "Kimia Moto rental", bonus: "Punctuality bonus", net: "Estimated net income per month" },
      sim: { base: "Deliveries at public prices", discount: "Volume discount ({p})", cod: "Cash-on-delivery fees", total: "Estimated monthly cost", per: "or {n} per order", none: "none" },
      dashStatus: { delivered: "Delivered", transit: "In transit", out: "Out for delivery", failed: "To reschedule" },
      invalidTracking: "Invalid tracking number (format KX-2026-000000)."
    }
  }
};
