/* Kimia Express — page bodies: pricing, business, network. */
"use strict";
const K = require("./lib.js"), C = K.C;
const { esc, L, href, fc, pic, head, field, sel, note, figure } = K;

function pricing(lang, base) {
  const U = C.ui[lang], P = U.pricing, Pr = C.prices, N = U.network;
  const sizeCell = s => "<td><b>" + esc(s.t[lang]) + "</b><small>" + esc(s.sub[lang]) + "</small></td>";
  const th = (cols, numFrom) => "<thead><tr>" + cols.map((c, i) => "<th" + (i >= numFrom ? ' class="num"' : "") + ">" + esc(c) + "</th>").join("") + "</tr></thead>";
  const urban = '<div class="table-wrap"><table>' + th(P.urbanCols, 1) + "<tbody>" + C.sizes.map(s => "<tr>" + sizeCell(s) + [0, 1, 2].map(z => '<td class="num">' + fc(Pr.urban[s.key] + z * Pr.zoneStep, lang) + "</td>").join("") + "</tr>").join("") + "</tbody></table></div>" + note(P.urbanNote);
  const kin = K.city("kin");
  const zones = '<div class="zones">' + [1, 2, 3].map(z => '<div class="zone z' + z + '"><h4>' + esc(P.zoneNames[z - 1]) + "</h4><p>" + kin.communes.filter(c => c[1] === z).map(c => esc(c[0])).join(", ") + "</p></div>").join("") + "</div>";
  const inter = '<div class="table-wrap"><table>' + th(P.interCols, 1) + "<tbody>" + C.sizes.map(s => "<tr>" + sizeCell(s) + '<td class="num">' + fc(Pr.road[s.key], lang) + '</td><td class="num">' + fc(Pr.air[s.key], lang) + "</td></tr>").join("") + "</tbody></table></div>" + note(P.interNote);
  const delays = '<div class="table-wrap"><table>' + th(P.delaysCols, 3) + "<tbody>" + C.cities.filter(c => c.key !== "kin").map(c => "<tr><td><b>" + esc(c.n) + "</b></td><td>" + esc(c.prov) + "</td><td>" + esc(N.modeNames[c.mode]) + '</td><td class="num">' + esc(K.days(c.days, lang)) + '</td><td class="num">' + esc(K.days(K.expressDays(c), lang)) + "</td></tr>").join("") + "</tbody></table></div>";
  const vol = '<form class="f" id="vol-form"><h3>' + esc(P.volT) + "</h3><p>" + esc(P.volLead) + '</p><div class="frow4">' + field(U.send.weight, '<input name="kg" type="number" min="0" step="0.1" value="4" inputmode="decimal">') + field(U.send.L, '<input name="dl" type="number" min="0" value="60" inputmode="numeric">') + field(U.send.W, '<input name="dw" type="number" min="0" value="40" inputmode="numeric">') + field(U.send.H, '<input name="dh" type="number" min="0" value="30" inputmode="numeric">') + '</div><div><button class="btn btn-dark btn-small" type="submit">' + esc(P.volBtn) + '</button></div><p class="ack" id="vol-out" aria-live="polite" hidden></p></form>';
  return K.pageHead(lang, base, { h1: P.h1, lead: P.lead, img: "traffic.jpg", cap: P.trafficCap }) +
    '<section class="tight-top"><div class="wrap grid-2"><div>' + head(null, P.estT, P.estLead) + K.quickWidget(lang, base) + "</div><div>" + vol + note(P.rateNote) + "</div></div></section>" +
    '<section class="alt" id="ville"><div class="wrap grid-2"><div>' + head(null, P.urbanT, P.urbanLead) + urban + "</div><div><h3 class=\"sub\">" + esc(P.zonesT) + "</h3>" + zones + "</div></div></section>" +
    '<section id="intervilles"><div class="wrap grid-2"><div>' + head(null, P.interT, P.interLead) + inter + "</div><div><h3 class=\"sub\">" + esc(P.delaysT) + "</h3>" + delays + "</div></div></section>" +
    '<section class="alt" id="options"><div class="wrap">' + head(null, P.optsT) + K.plainCards(P.opts, "grid-3") + "</div></section>" +
    '<section><div class="wrap grid-2"><div>' + head(null, P.payT, P.payLead) + K.payChips(lang) + "</div><div>" + head(null, P.docsT) + K.docList(lang, [C.docs[1], C.docs[0], C.docs[2]], U.common.download) + "</div></div></section>";
}

function business(lang, base) {
  const U = C.ui[lang], B = U.business, J = C.js[lang];
  const sol = '<div class="grid-2 cards-2">' + B.sol.map(s => '<article class="card svc wide"><div class="pic"><img src="' + pic(base, s[2]) + '" alt="" loading="lazy"></div><div class="body"><h3>' + esc(s[0]) + "</h3><p>" + esc(s[1]) + "</p></div></article>").join("") + "</div>";
  const tiers = '<div class="table-wrap"><table><thead><tr>' + B.tiersCols.map(c => "<th>" + esc(c) + "</th>").join("") + "</tr></thead><tbody>" + B.tiers.map(t => '<tr><td class="num-l"><b>' + esc(t[0]) + '</b></td><td><span class="pill">' + esc(t[1]) + "</span></td><td>" + esc(t[2]) + "</td><td>" + esc(t[3]) + "</td></tr>").join("") + "</tbody></table></div>";
  const sim = '<form class="f" id="sim-form"><h3>' + esc(B.simT) + '</h3><p class="note">' + esc(B.simLead) + '</p><div class="frow">' + field(B.simOrders, '<input name="orders" type="number" min="1" value="600" inputmode="numeric">') + field(B.simUrban, '<input name="urban" type="number" min="0" max="100" value="80" inputmode="numeric">') + '</div><div class="frow">' + field(B.simCod, '<input name="cod" type="number" min="0" max="100" value="60" inputmode="numeric">') + field(B.simAvg, '<input name="avg" type="number" min="0" step="1000" value="45000" inputmode="numeric">') + '</div><dl class="lines" id="sim-out" aria-live="polite"></dl></form>';
  const D = B.dash;
  const dash = '<div class="dash"><div class="dash-top"><span class="dots" aria-hidden="true"><i></i><i></i><i></i></span><b>' + esc(D.title) + '</b></div><div class="dash-kpis">' + D.kpis.map(k => "<div><b>" + esc(k[0]) + "</b><span>" + esc(k[1]) + "</span></div>").join("") + '</div><div class="dash-cod"><span>' + esc(D.codLabel) + "</span><b>" + esc(D.codValue) + '</b></div><div class="table-wrap flat"><table class="compact"><thead><tr>' + D.cols.map((c, i) => "<th" + (i === 3 ? ' class="num"' : "") + ">" + esc(c) + "</th>").join("") + "</tr></thead><tbody>" + D.rows.map(r => '<tr><td class="mono">' + r[0] + "</td><td>" + esc(r[1]) + '</td><td><span class="status s-' + r[2] + '">' + esc(J.dashStatus[r[2]]) + '</span></td><td class="num">' + esc(r[3]) + "</td></tr>").join("") + "</tbody></table></div></div>";
  const code = '<pre class="code" tabindex="0"><code><span class="c-cmd">curl</span> https://api.kimia-express.cd/v1/shipments \\\n  -H <span class="c-str">"Authorization: Bearer sk_test_4f9a…"</span> \\\n  -d origin_city=kin -d origin_commune=Gombe \\\n  -d destination_city=lub -d destination_commune=Kampemba \\\n  -d size=s -d cod_amount=85000 \\\n  -d recipient_phone=<span class="c-str">"+243810000000"</span>\n\n<span class="c-com"># 201 Created</span>\n{\n  <span class="c-key">"tracking_number"</span>: <span class="c-str">"KX-2026-512051"</span>,\n  <span class="c-key">"price"</span>: 55000,\n  <span class="c-key">"currency"</span>: <span class="c-str">"CDF"</span>,\n  <span class="c-key">"mode"</span>: <span class="c-str">"air"</span>,\n  <span class="c-key">"estimated_delivery"</span>: <span class="c-str">"2026-09-17"</span>,\n  <span class="c-key">"label_pdf"</span>: <span class="c-str">"…/labels/KX-2026-512051.pdf"</span>\n}</code></pre>';
  const F = B.form, cities = C.cities.map(c => c.n);
  const form = '<form class="f" id="biz-form"><div class="frow">' + field(F.company, '<input name="company" required>') + field(F.sector, sel("sector", F.sectors)) + '</div><div class="frow">' + field(F.city, sel("city", cities)) + field(F.volume, sel("volume", F.volumes)) + '</div><fieldset class="checks"><legend>' + esc(F.needs) + "</legend>" + F.needsList.map(n => '<label class="check"><input type="checkbox" name="needs" value="' + esc(n) + '"><span>' + esc(n) + "</span></label>").join("") + '</fieldset><div class="frow">' + field(F.contact, '<input name="contact" required autocomplete="name">') + field(F.phone, '<input name="phone" type="tel" required autocomplete="tel">') + "</div>" + field(F.email, '<input name="email" type="email" required autocomplete="email">') + field(F.msg, '<textarea name="msg" rows="3"></textarea>') + '<div><button class="btn btn-primary" type="submit">' + esc(F.send) + '</button></div><div id="biz-out"></div></form>';
  return K.pageHead(lang, base, { h1: B.h1, lead: B.lead, img: "mall.jpg", cap: B.mallCap, ctas: '<a class="btn btn-primary" href="#compte">' + esc(B.cta1) + '</a><a class="btn btn-outline light" href="#api">' + esc(B.cta2) + "</a>" }) +
    '<section><div class="wrap">' + head(null, B.solT) + sol + "</div></section>" +
    '<section class="alt" id="remises"><div class="wrap grid-2"><div>' + head(null, B.tiersT) + tiers + "</div><div>" + sim + "</div></div></section>" +
    '<section><div class="wrap grid-2 middle"><div>' + head(null, B.dashT, B.dashLead) + "</div>" + dash + "</div></section>" +
    '<section class="dark" id="api"><div class="wrap grid-2"><div>' + head(null, B.apiT, B.apiLead) + K.plainCards(B.integrations, "grid-2") + "</div><div>" + code + note(B.apiNote) + "</div></div></section>" +
    '<section><div class="wrap grid-2 middle"><div>' + figure(base, "supermarket.jpg", B.marketCap, "tall") + "</div><div>" + head(null, B.casesT) + '<div class="stack">' + B.cases.map(c => '<div class="card plain"><h3>' + esc(c[0]) + "</h3><p>" + esc(c[1]) + "</p></div>").join("") + "</div>" + note(B.casesNote) + "</div></div></section>" +
    '<section class="alt" id="compte"><div class="wrap grid-2"><div>' + head(null, B.formT, B.formLead) + '<div class="callout"><b>' + esc(U.help.points[2][0]) + '</b><a href="' + K.tel(C.company.business) + '">' + esc(C.company.business) + '</a><a href="mailto:' + C.company.businessEmail + '">' + esc(C.company.businessEmail) + "</a><span>" + esc(U.help.points[2][4]) + '</span></div><div class="spacer"></div>' + K.docList(lang, [C.docs[4], C.docs[5], C.docs[1]], U.common.download) + "</div>" + form + "</div></section>";
}

function network(lang, base) {
  const U = C.ui[lang], N = U.network;
  const relayCount = k => C.relays.filter(r => r.city === k).length;
  const cards = '<div class="grid-3">' + C.cityCards.map(cc => { const c = K.city(cc.key); return '<article class="card svc" id="ville-' + c.key + '"><div class="pic"><img src="' + pic(base, cc.img) + '" alt="" loading="lazy"></div><div class="body"><span class="meta">' + esc(c.prov) + " · " + esc(N.modeNames[c.mode]) + "</span><h3>" + esc(c.n) + "</h3><p>" + esc(cc.d[lang]) + '</p><p class="from">' + (c.key === "kin" ? esc(K.days(0, lang)) : esc(K.days(c.days, lang)) + " · express " + esc(K.days(K.expressDays(c), lang))) + "</p></div></article>"; }).join("") + "</div>";
  const table = '<div class="table-wrap"><table><thead><tr>' + N.cols.map((c, i) => "<th" + (i === 3 || i === 4 || i === 6 ? ' class="num"' : "") + ">" + esc(c) + "</th>").join("") + "</tr></thead><tbody>" +
    C.cities.map(c => "<tr><td><b>" + esc(c.n) + "</b></td><td>" + esc(c.prov) + "</td><td>" + esc(N.modeNames[c.mode]) + '</td><td class="num">' + esc(c.key === "kin" ? "—" : K.days(c.days, lang)) + '</td><td class="num">' + esc(c.key === "kin" ? "—" : K.days(K.expressDays(c), lang)) + "</td><td>" + esc(c.urban ? N.urbanYes : N.urbanNo) + '</td><td class="num">' + relayCount(c.key) + "</td></tr>").join("") + "</tbody></table></div>";
  const relays = '<div class="filters"><select id="relay-city" aria-label="' + esc(N.allCities) + '"><option value="">' + esc(N.allCities) + "</option>" + C.cities.map(c => '<option value="' + c.key + '">' + esc(c.n) + " (" + relayCount(c.key) + ")</option>").join("") + '</select><input id="relay-q" type="search" placeholder="' + esc(N.search) + '" aria-label="' + esc(N.search) + '"></div>' +
    '<ul class="relays" id="relay-list">' + C.relays.map(r => { const c = K.city(r.city), commune = L(r.c, lang); return '<li data-city="' + r.city + '" data-text="' + esc([r.n, commune, c.n, r.a[lang]].join(" ").toLowerCase()) + '"><div class="relay-main"><span class="kind k-' + r.kind + '">' + esc(N.kinds[r.kind]) + "</span><b>" + esc(r.n) + "</b><span>" + esc(commune) + " · " + esc(c.n) + "</span><span>" + esc(r.a[lang]) + '</span><small>' + esc(r.h[lang]) + '</small></div><ul class="tags">' + r.s.map(s => "<li>" + esc(N.services[s]) + "</li>").join("") + "</ul></li>"; }).join("") + '</ul><p class="empty" id="relay-empty" hidden></p>';
  return K.pageHead(lang, base, { h1: N.h1, lead: N.lead, img: "boulevard.jpg", cap: N.boulevardCap, ctas: '<a class="btn btn-primary" href="#relais">' + esc(N.relayT) + "</a>" }) +
    '<section><div class="wrap grid-2 middle"><div>' + head(null, N.mapT, N.mapLead) + '<h3 class="sub">' + esc(N.modesT) + "</h3>" + K.plainCards(N.modes, "stack") + '</div><div class="map-wrap light">' + K.networkMap(lang) + "</div></div></section>" +
    '<section class="alt"><div class="wrap">' + head(null, N.citiesT) + cards + "</div></section>" +
    '<section><div class="wrap">' + head(null, N.tableT) + table + "</div></section>" +
    '<section class="alt" id="relais"><div class="wrap">' + head(null, N.relayT, N.relayLead) + relays + "</div></section>";
}

module.exports = { pricing, business, network };
