/* Kimia Express — page bodies: couriers, help, about. */
"use strict";
const K = require("./lib.js"), C = K.C;
const { esc, href, pic, head, field, sel, note, figure } = K;

function couriers(lang, base) {
  const U = C.ui[lang], R = U.couriers, F = R.form;
  const range = (label, name, min, max, value) => '<label class="field range"><span>' + esc(label) + ' <output data-range-out="' + name + '">' + value + '</output></span><input type="range" name="' + name + '" min="' + min + '" max="' + max + '" value="' + value + '"></label>';
  const earn = '<form class="f" id="earn-form"><h3>' + esc(R.earnT) + '</h3><p class="note">' + esc(R.earnLead) + '</p><div class="frow">' + range(R.perDay, "perDay", 6, 30, 18) + range(R.daysWk, "daysWk", 4, 7, 6) + "</div>" +
    '<fieldset class="checks"><legend>' + esc(R.moto) + '</legend><label class="radio"><input type="radio" name="moto" value="own" checked><span>' + esc(R.motoOwn) + '</span></label><label class="radio"><input type="radio" name="moto" value="rent"><span>' + esc(R.motoRent) + "</span></label></fieldset>" +
    '<label class="check"><input type="checkbox" name="bonus" checked><span>' + esc(R.bonus) + '</span></label><dl class="lines" id="earn-out" aria-live="polite"></dl></form>';
  const cities = [...new Set(C.jobs.map(j => j.city))], depts = [...new Set(C.jobs.map(j => j.dept[lang]))], titles = [...new Set(C.jobs.map(j => j.t[lang]))];
  const jobs = '<div class="filters"><select id="job-city" aria-label="' + esc(R.allCities) + '"><option value="">' + esc(R.allCities) + "</option>" + cities.map(c => '<option value="' + esc(c) + '">' + esc(c) + "</option>").join("") + '</select><select id="job-dept" aria-label="' + esc(R.allDepts) + '"><option value="">' + esc(R.allDepts) + "</option>" + depts.map(d => '<option value="' + esc(d) + '">' + esc(d) + "</option>").join("") + "</select></div>" +
    '<ul class="jobs" id="job-list">' + C.jobs.map(j => '<li data-city="' + esc(j.city) + '" data-dept="' + esc(j.dept[lang]) + '"><div><b>' + esc(j.t[lang]) + "</b><small>" + esc(j.city) + " · " + esc(j.dept[lang]) + " · " + esc(j.type[lang]) + " · " + esc(R.closes) + " " + esc(K.fmtDate(j.close, lang)) + '</small></div><button class="btn btn-primary btn-small" type="button" data-apply="' + esc(j.t[lang]) + '">' + esc(R.cta1) + "</button></li>").join("") + '</ul><p class="empty" id="job-empty" hidden></p>';
  const form = '<form class="f" id="apply-form"><div class="frow">' + field(F.name, '<input name="name" id="ap-name" required autocomplete="name">') + field(F.phone, '<input name="phone" type="tel" required autocomplete="tel">') + '</div><div class="frow">' + field(F.city, sel("city", F.cities)) + field(F.job, '<select name="job" id="ap-job">' + titles.map(t => "<option>" + esc(t) + "</option>").join("") + "</select>") + '</div><div class="frow">' + field(F.moto, sel("moto", F.motoOpts)) + field(F.licence, '<input name="licence">') + "</div>" + field(F.cv, '<input name="cv" type="file" accept="application/pdf,image/*">') + field(F.msg, '<textarea name="msg" rows="3"></textarea>') + '<div><button class="btn btn-primary" type="submit">' + esc(F.send) + '</button></div><div id="apply-out"></div></form>';
  return K.pageHead(lang, base, { h1: R.h1, lead: R.lead, img: "goma-motos.jpg", cap: U.home.drvCap, ctas: '<a class="btn btn-primary" href="#postuler">' + esc(R.cta1) + '</a><a class="btn btn-outline light" href="#emplois">' + esc(R.cta2) + "</a>" }) +
    '<section><div class="wrap">' + head(null, R.whyT) + K.plainCards(R.why) + "</div></section>" +
    '<section class="alt"><div class="wrap grid-2">' + earn + "<div>" + figure(base, "riders.jpg", R.ridersCap) + '<h3 class="sub">' + esc(R.reqT) + '</h3><ul class="ticks">' + R.req.map(r => "<li>" + esc(r) + "</li>").join("") + "</ul></div></div></section>" +
    '<section><div class="wrap grid-2 middle"><div class="callout big"><p class="eyebrow">' + esc(R.motoT) + "</p><h2>" + esc(R.motoT) + '</h2><p class="lead">' + esc(R.motoLead) + "</p></div><div>" + head(null, R.stepsT) + K.plainCards(R.steps, "grid-2") + "</div></div></section>" +
    '<section class="alt" id="emplois"><div class="wrap">' + head(null, R.jobsT) + jobs + "</div></section>" +
    '<section id="postuler"><div class="wrap grid-2"><div>' + head(null, R.applyT, R.applyLead) + '<div class="callout"><b>' + esc(U.help.points[3][0]) + '</b><a href="' + K.tel(C.company.couriers) + '">' + esc(C.company.couriers) + '</a><a href="mailto:' + C.company.jobsEmail + '">' + esc(C.company.jobsEmail) + "</a><span>" + esc(U.help.points[3][4]) + '</span></div><div class="spacer"></div>' + K.docList(lang, [C.docs[6]], U.common.download) + "</div>" + form + "</div></section>";
}

function help(lang, base) {
  const U = C.ui[lang], H = U.help, CF = H.claimForm, F = H.form;
  const faq = '<div class="filters"><input id="faq-q" type="search" placeholder="' + esc(H.search) + '" aria-label="' + esc(H.search) + '"><select id="faq-cat" aria-label="' + esc(H.allCats) + '"><option value="">' + esc(H.allCats) + "</option>" + Object.keys(H.cats).map(k => '<option value="' + k + '">' + esc(H.cats[k]) + "</option>").join("") + "</select></div>" + K.faqList(lang, C.faqs, "faq-list") + '<p class="empty" id="faq-empty" hidden></p>';
  const claim = '<form class="f" id="claim-form"><div class="frow">' + field(CF.tracking, '<input name="tracking" class="mono" required placeholder="KX-2026-000000" autocomplete="off">') + field(CF.type, sel("type", CF.types)) + '</div><div class="frow">' + field(CF.name, '<input name="name" required autocomplete="name">') + field(CF.phone, '<input name="phone" type="tel" required autocomplete="tel">') + "</div>" + field(CF.msg, '<textarea name="msg" rows="4" required></textarea>') + field(CF.photo, '<input name="photos" type="file" accept="image/*" multiple>') + '<div><button class="btn btn-primary" type="submit">' + esc(CF.send) + '</button></div><div id="claim-out"></div></form>';
  const point = p => { const n = C.company[p[2]], link = p[2] === "whatsapp" ? K.wa(n) : K.tel(n); return "<div><b>" + esc(p[0]) + "</b><span>" + esc(p[1]) + '</span><a href="' + link + '"' + (p[2] === "whatsapp" ? ' rel="noopener"' : "") + ">" + esc(n) + '</a><a href="mailto:' + C.company[p[3]] + '">' + esc(C.company[p[3]]) + "</a><small>" + esc(p[4]) + "</small></div>"; };
  const contact = '<form class="f" id="contact-form"><div class="frow">' + field(F.name, '<input name="name" required autocomplete="name">') + field(F.email, '<input name="email" type="email" required autocomplete="email">') + "</div>" + field(F.subject, sel("subject", F.subjects)) + field(F.msg, '<textarea name="msg" rows="4" required></textarea>') + '<div><button class="btn btn-dark" type="submit">' + esc(F.send) + '</button></div><div id="contact-out"></div></form>';
  return K.pageHead(lang, base, { h1: H.h1, lead: H.lead, img: "gombe.jpg", cap: H.gombeCap, ctas: '<a class="btn btn-primary" href="#reclamation">' + esc(H.claimT) + '</a><a class="btn btn-outline light" href="#contact">' + esc(H.contactT) + "</a>" }) +
    '<section><div class="wrap narrow">' + head(null, H.faqT) + faq + "</div></section>" +
    '<section class="alt" id="reclamation"><div class="wrap grid-2"><div>' + head(null, H.claimT, H.claimLead) + '<div class="callout"><b>' + esc(H.points[4][0]) + '</b><a href="' + K.tel(C.company.phone) + '">' + esc(C.company.phone) + '</a><a href="mailto:' + C.company.claimsEmail + '">' + esc(C.company.claimsEmail) + "</a><span>" + esc(H.points[4][4]) + "</span></div></div>" + claim + "</div></section>" +
    '<section id="interdits"><div class="wrap">' + head(null, H.prohibT) + '<div class="grid-2">' + H.prohib.map((g, i) => '<div class="prohib p' + i + '"><h3>' + esc(g[0]) + '</h3><ul class="' + (i === 0 ? "x-list" : "ticks") + '">' + g[1].map(x => "<li>" + esc(x) + "</li>").join("") + "</ul></div>").join("") + "</div></div></section>" +
    '<section class="alt" id="contact"><div class="wrap">' + head(null, H.contactT) + '<div class="contacts">' + H.points.map(point).join("") + '</div><p class="note">' + esc(C.company.hq[lang]) + "</p></div></section>" +
    '<section><div class="wrap grid-2"><div>' + head(null, H.writeT) + contact + "</div><div>" + head(null, H.docsT) + K.docList(lang, [C.docs[0], C.docs[3], C.docs[2], C.docs[1]], U.common.download) + "</div></div></section>" +
    '<section class="alt legal" id="mentions"><div class="wrap narrow">' + head(null, H.legalT) + "<dl>" + H.legal.map(l => "<dt>" + esc(l[0]) + "</dt><dd>" + esc(l[1]) + "</dd>").join("") + "</dl></div></section>";
}

function about(lang, base) {
  const U = C.ui[lang], A = U.about;
  const cats = [...new Set(C.news.map(n => n.cat[lang]))];
  return K.pageHead(lang, base, { h1: A.h1, lead: A.lead, img: "kin-aerial.jpg", cap: A.aerialCap }) +
    '<section><div class="wrap grid-2 middle"><div><p class="eyebrow">' + esc(A.missionT) + '</p><h2 class="statement">' + esc(A.mission) + '</h2></div><div><p class="eyebrow">' + esc(A.figuresT) + "</p>" + K.kpiRow(lang, C.figures).replace('class="kpi-row"', 'class="kpi-row two"') + note(U.illustrative) + "</div></div></section>" +
    '<section class="alt"><div class="wrap grid-2"><div>' + head(null, A.historyT) + '<ul class="timeline">' + C.timeline.map(t => '<li><span class="y">' + t.y + "</span><p>" + esc(t[lang]) + "</p></li>").join("") + "</ul></div><div>" + figure(base, "traffic.jpg", A.trafficCap) + '<h3 class="sub">' + esc(A.whyMotoT) + '</h3><p class="lead">' + esc(A.whyMoto) + '</p><div class="spacer"></div>' + figure(base, "rider.jpg", U.home.photoCap, "portrait") + "</div></div></section>" +
    '<section><div class="wrap">' + head(null, A.leadersT) + '<div class="people">' + C.leaders.map(p => '<div class="person"><span class="initials" aria-hidden="true">' + p.n.split(" ").map(w => w[0]).slice(0, 2).join("") + "</span><b>" + esc(p.n) + "</b><span>" + esc(p.r[lang]) + "</span><p>" + esc(p.b[lang]) + "</p></div>").join("") + "</div>" + note(U.illustrative) + "</div></section>" +
    '<section class="dark"><div class="wrap">' + head(null, A.commitT) + K.plainCards(A.commit) + "</div></section>" +
    '<section id="actualites"><div class="wrap">' + head(null, A.newsT) + '<div class="filters"><input id="news-q" type="search" placeholder="' + esc(A.search) + '" aria-label="' + esc(A.search) + '"><select id="news-cat" aria-label="' + esc(A.allCat) + '"><option value="">' + esc(A.allCat) + "</option>" + cats.map(c => '<option value="' + esc(c) + '">' + esc(c) + "</option>").join("") + '</select></div><ul class="news" id="news-list">' + C.news.map(n => K.newsItem(n, lang)).join("") + '</ul><p class="empty" id="news-empty" hidden></p></div></section>' +
    '<section class="alt"><div class="wrap grid-2"><div><p class="eyebrow">' + esc(A.pressT) + '</p><p class="lead"><a href="mailto:' + C.company.press + '">' + esc(C.company.press) + '</a><br><a href="' + K.tel(C.company.phone) + '">' + esc(C.company.phone) + "</a></p></div><div>" + K.docList(lang, [C.docs[6], C.docs[3]], U.common.download) + "</div></div></section>";
}

module.exports = { couriers, help, about };
